// Code generated by go generate; DO NOT EDIT.
package ctxkey

const (
	ChatMessage uint32 = 1
	FoodTo uint32 = 2
	HealAmount uint32 = 3
	HurtDamage uint32 = 4
	HurtAttackImmunityMillis uint32 = 5
	DeathKeepInventory uint32 = 6
	RespawnPosX uint32 = 7
	RespawnPosY uint32 = 8
	RespawnPosZ uint32 = 9
	RespawnWorldName uint32 = 10
	BlockBreakXP uint32 = 11
	AttackForce uint32 = 12
	AttackHeight uint32 = 13
	AttackCritical uint32 = 14
	ExperienceAmount uint32 = 15
	SleepSendReminder uint32 = 16
	LecternNewPage uint32 = 17
	ItemDamageAmount uint32 = 18
	ItemPickupCount uint32 = 19
	TransferAddr uint32 = 20
	JoinCancelMessage uint32 = 21
)

var byName = map[string]uint32{
	"chat.message": ChatMessage,
	"food.to": FoodTo,
	"heal.amount": HealAmount,
	"hurt.damage": HurtDamage,
	"hurt.attack_immunity_millis": HurtAttackImmunityMillis,
	"death.keep_inventory": DeathKeepInventory,
	"respawn.pos_x": RespawnPosX,
	"respawn.pos_y": RespawnPosY,
	"respawn.pos_z": RespawnPosZ,
	"respawn.world_name": RespawnWorldName,
	"block_break.xp": BlockBreakXP,
	"attack.force": AttackForce,
	"attack.height": AttackHeight,
	"attack.critical": AttackCritical,
	"experience.amount": ExperienceAmount,
	"sleep.send_reminder": SleepSendReminder,
	"lectern.new_page": LecternNewPage,
	"item.damage_amount": ItemDamageAmount,
	"item.pickup_count": ItemPickupCount,
	"transfer.addr": TransferAddr,
	"join.cancel_message": JoinCancelMessage,
}

func ID(name string) (uint32, bool) {
	id, ok := byName[name]
	return id, ok
}
