namespace BedrockPlugin.Sdk.Guest;

public interface IEventPayload;

public sealed record MovePayload(Vec3 NewPos, Rotation NewRot) : IEventPayload;
public sealed record JumpPayload(PlayerIdentity Info) : IEventPayload;
public sealed record TeleportPayload(Vec3 Pos) : IEventPayload;
public sealed record ChangeWorldPayload(WorldData Before, WorldData After) : IEventPayload;
public sealed record ToggleSprintPayload(bool After) : IEventPayload;
public sealed record ToggleSneakPayload(bool After) : IEventPayload;
public sealed record ChatPayload(string Message) : IEventPayload;
public sealed record FoodLossPayload(int From, int To) : IEventPayload;
public sealed record HealPayload(double Amount, HealingSourceData Source) : IEventPayload;
public sealed record HurtPayload(double Damage, bool Immune, long AttackImmunityMillis, DamageSourceData Source) : IEventPayload;
public sealed record DeathPayload(DamageSourceData Source, bool KeepInventory) : IEventPayload;
public sealed record RespawnPayload(Vec3 Pos, string WorldName) : IEventPayload;
public sealed record SkinChangePayload(SkinData Skin) : IEventPayload;
public sealed record FireExtinguishPayload(Pos Pos) : IEventPayload;
public sealed record StartBreakPayload(Pos Pos) : IEventPayload;
public sealed record BlockBreakPayload(Pos Pos, IReadOnlyList<ItemStackData> Drops, int Xp) : IEventPayload;
public sealed record BlockPlacePayload(Pos Pos, BlockData Block) : IEventPayload;
public sealed record BlockPickPayload(Pos Pos, BlockData Block) : IEventPayload;
public sealed record ItemUsePayload() : IEventPayload;
public sealed record ItemUseOnBlockPayload(Pos Pos, byte Face, Vec3 ClickPos) : IEventPayload;
public sealed record ItemUseOnEntityPayload(EntityData Entity) : IEventPayload;
public sealed record ItemReleasePayload(ItemStackData Item, long DurationMillis) : IEventPayload;
public sealed record ItemConsumePayload(ItemStackData Item) : IEventPayload;
public sealed record AttackEntityPayload(EntityData Entity, double Force, double Height, bool Critical) : IEventPayload;
public sealed record ExperienceGainPayload(int Amount) : IEventPayload;
public sealed record PunchAirPayload() : IEventPayload;
public sealed record SignEditPayload(Pos Pos, bool FrontSide, string OldText, string NewText) : IEventPayload;
public sealed record SleepPayload(bool SendReminder) : IEventPayload;
public sealed record LecternPageTurnPayload(Pos Pos, int OldPage, int NewPage) : IEventPayload;
public sealed record ItemDamagePayload(ItemStackData Item, int Damage) : IEventPayload;
public sealed record ItemPickupPayload(ItemStackData Item) : IEventPayload;
public sealed record HeldSlotChangePayload(int From, int To) : IEventPayload;
public sealed record ItemDropPayload(ItemStackData Item) : IEventPayload;
public sealed record TransferPayload(string Address) : IEventPayload;
public sealed record CommandExecutionPayload(CommandData Command) : IEventPayload;
public sealed record QuitPayload(PlayerIdentity Info) : IEventPayload;
public sealed record DiagnosticsPayload(DiagnosticsData Diagnostics) : IEventPayload;
public sealed record JoinPayload(PlayerIdentity Info) : IEventPayload;
public sealed record PluginCommandPayload(uint HandlerId, IReadOnlyList<string> Args) : IEventPayload;
