// Code generated by generator. DO NOT EDIT.
using System.Collections.Generic;

namespace BedrockPlugin.Sdk.Guest;

public interface IGuestHost
{
    bool AddPlayerFood(ulong playerId, int points);

    IReadOnlyList<string> BlockNames();

    void ConsoleMessage(string pluginName, string message);

    bool EventCancel(ulong requestKey);

    bool EventSetItemDrop(ulong requestKey, ItemStackData stack);

    IReadOnlyList<string> ItemNames();

    IReadOnlyList<string> ManagePlugins(uint action, string target);

    IReadOnlyList<string> OnlinePlayerNames();

    double PlayerAbsorption(ulong playerId);

    IReadOnlyList<ItemStackData> PlayerArmourItems(ulong playerId);

    bool PlayerCloseDialogue(ulong playerId);

    bool PlayerCloseForm(ulong playerId);

    bool PlayerCrawling(ulong playerId);

    bool PlayerDead(ulong playerId);

    string PlayerDeviceID(ulong playerId);

    string PlayerDeviceModel(ulong playerId);

    IReadOnlyList<ItemStackData> PlayerEnderChestItems(ulong playerId);

    int PlayerExperience(ulong playerId);

    int PlayerExperienceLevel(ulong playerId);

    double PlayerExperienceProgress(ulong playerId);

    bool PlayerExtinguish(ulong playerId);

    double PlayerFlightSpeed(ulong playerId);

    bool PlayerFlying(ulong playerId);

    int PlayerFood(ulong playerId);

    int PlayerGameMode(ulong playerId);

    bool PlayerGliding(ulong playerId);

    ulong PlayerHandle(ulong playerId);

    double PlayerHealth(ulong playerId);

    bool PlayerImmobile(ulong playerId);

    IReadOnlyList<ItemStackData> PlayerInventoryItems(ulong playerId);

    bool PlayerInvisible(ulong playerId);

    bool PlayerJump(ulong playerId);

    TimeSpan PlayerLatency(ulong playerId);

    ItemStackData PlayerMainHandItem(ulong playerId);

    double PlayerMaxHealth(ulong playerId);

    void PlayerMessage(ulong playerId, string message);

    bool PlayerMoveItemsToInventory(ulong playerId);

    string PlayerName(ulong playerId);

    string PlayerNameTag(ulong playerId);

    ItemStackData PlayerOffHandItem(ulong playerId);

    bool PlayerOnGround(ulong playerId);

    string PlayerScoreTag(ulong playerId);

    string PlayerSelfSignedID(ulong playerId);

    bool PlayerSendMenuForm(ulong playerId, MenuFormData value);

    bool PlayerSendModalForm(ulong playerId, ModalFormData value);

    bool PlayerSneaking(ulong playerId);

    double PlayerSpeed(ulong playerId);

    bool PlayerSprinting(ulong playerId);

    bool PlayerSwimming(ulong playerId);

    bool PlayerSwingArm(ulong playerId);

    bool PlayerUseItem(ulong playerId);

    bool PlayerUsingItem(ulong playerId);

    double PlayerVerticalFlightSpeed(ulong playerId);

    bool PlayerWake(ulong playerId);

    string PlayerXUID(ulong playerId);

    bool RegisterCommand(string pluginName, string name, string description, IReadOnlyList<string> aliases, uint handlerId, IReadOnlyList<CommandOverloadSpec> overloads);

    ulong ResolvePlayerByName(string name);

    bool SetPlayerAbsorption(ulong playerId, double value);

    bool SetPlayerArmourItems(ulong playerId, IReadOnlyList<ItemStackData> items);

    bool SetPlayerCrawling(ulong playerId, bool value);

    bool SetPlayerEnderChestItems(ulong playerId, IReadOnlyList<ItemStackData> items);

    bool SetPlayerExperienceLevel(ulong playerId, int value);

    bool SetPlayerExperienceProgress(ulong playerId, double value);

    bool SetPlayerFlightSpeed(ulong playerId, double value);

    bool SetPlayerFlying(ulong playerId, bool value);

    bool SetPlayerFood(ulong playerId, int food);

    bool SetPlayerGameMode(ulong playerId, int mode);

    bool SetPlayerGliding(ulong playerId, bool value);

    bool SetPlayerHealth(ulong playerId, double health);

    bool SetPlayerHeldSlot(ulong playerId, int slot);

    bool SetPlayerImmobile(ulong playerId, bool value);

    bool SetPlayerInventoryItems(ulong playerId, IReadOnlyList<ItemStackData> items);

    bool SetPlayerInvisible(ulong playerId, bool value);

    bool SetPlayerMainHandItem(ulong playerId, ItemStackData stack);

    bool SetPlayerMaxHealth(ulong playerId, double value);

    bool SetPlayerNameTag(ulong playerId, string value);

    bool SetPlayerOffHandItem(ulong playerId, ItemStackData stack);

    bool SetPlayerOnFireMillis(ulong playerId, long millis);

    bool SetPlayerScoreTag(ulong playerId, string value);

    bool SetPlayerShowCoordinates(ulong playerId, bool value);

    bool SetPlayerSneaking(ulong playerId, bool value);

    bool SetPlayerSpeed(ulong playerId, double value);

    bool SetPlayerSprinting(ulong playerId, bool value);

    bool SetPlayerSwimming(ulong playerId, bool value);

    bool SetPlayerVerticalFlightSpeed(ulong playerId, double value);

    IReadOnlyList<string> WorldNames();

}
