// Code generated by generator. DO NOT EDIT.
using System;
using System.Collections.Generic;

namespace BedrockPlugin.Sdk.Guest;

public sealed partial record BlockData(bool Present, string Name, IReadOnlyDictionary<string, string> Properties);

public sealed partial record CommandData(string Name, string Description, string Usage, IReadOnlyList<string> Args);

public sealed partial record CommandOverloadSpec(IReadOnlyList<CommandParameterSpec> Parameters);

public enum CommandParameterKind : byte
{
    Enum = 2,
    PluginAvailable = 4,
    PluginLoaded = 5,
    String = 0,
    Subcommand = 3,
    Target = 6,
    Text = 1,
}

public sealed partial record CommandParameterSpec(string Name, CommandParameterKind Kind, bool Optional, IReadOnlyList<string> EnumOptions);

public sealed partial record DamageSourceData(bool Present, string Type, bool ReducedByArmour, bool ReducedByResistance, bool Fire, bool IgnoreTotem);

public sealed partial record DiagnosticsData(double AverageFramesPerSecond, double AverageServerSimTickTime, double AverageClientSimTickTime, double AverageBeginFrameTime, double AverageInputTime, double AverageRenderTime, double AverageEndFrameTime, double AverageRemainderTimePercent, double AverageUnaccountedTimePercent);

public sealed partial record EntityData(bool Present, bool HasHandle, string Uuid, string Type, Vec3 Position, Rotation Rotation);

public sealed partial record HealingSourceData(bool Present, string Type);

public sealed partial record ItemStackData(int Count, bool HasItem, string ItemName, int ItemMeta, string CustomName);

public sealed partial record MenuFormData(string Title, string Body, IReadOnlyList<string> Buttons);

public sealed partial record ModalFormData(string Title, string Body, string Confirm, string Cancel);

public sealed partial record PlayerIdentity(string Name, string Uuid, string Xuid);

public sealed partial record Pos(int X, int Y, int Z);

public sealed partial record Rotation(double Yaw, double Pitch);

public sealed partial record SkinData(bool Present, int Width, int Height, bool Persona, string PlayFabId, string FullId);

public sealed partial record Vec3(double X, double Y, double Z);

public sealed partial record WorldData(bool Present, string Name, string Dimension);

