// Code generated by go generate; DO NOT EDIT.
package guest

type playerHost interface {
	PlayerHealth(playerID uint64) float64
	SetPlayerHealth(playerID uint64, health float64) bool
	PlayerFood(playerID uint64) int32
	SetPlayerFood(playerID uint64, food int32) bool
	PlayerName(playerID uint64) string
	PlayerGameMode(playerID uint64) int32
	SetPlayerGameMode(playerID uint64, mode int32) bool
	PlayerXUID(playerID uint64) string
	PlayerDeviceID(playerID uint64) string
	PlayerDeviceModel(playerID uint64) string
	PlayerSelfSignedID(playerID uint64) string
	PlayerNameTag(playerID uint64) string
	SetPlayerNameTag(playerID uint64, value string) bool
	PlayerScoreTag(playerID uint64) string
	SetPlayerScoreTag(playerID uint64, value string) bool
	PlayerAbsorption(playerID uint64) float64
	SetPlayerAbsorption(playerID uint64, value float64) bool
	PlayerMaxHealth(playerID uint64) float64
	SetPlayerMaxHealth(playerID uint64, value float64) bool
	PlayerSpeed(playerID uint64) float64
	SetPlayerSpeed(playerID uint64, value float64) bool
	PlayerFlightSpeed(playerID uint64) float64
	SetPlayerFlightSpeed(playerID uint64, value float64) bool
	PlayerVerticalFlightSpeed(playerID uint64) float64
	SetPlayerVerticalFlightSpeed(playerID uint64, value float64) bool
	PlayerExperience(playerID uint64) int32
	PlayerExperienceLevel(playerID uint64) int32
	SetPlayerExperienceLevel(playerID uint64, value int32) bool
	PlayerExperienceProgress(playerID uint64) float64
	SetPlayerExperienceProgress(playerID uint64, value float64) bool
	PlayerOnGround(playerID uint64) bool
	PlayerSneaking(playerID uint64) bool
	SetPlayerSneaking(playerID uint64, value bool) bool
	PlayerSprinting(playerID uint64) bool
	SetPlayerSprinting(playerID uint64, value bool) bool
	PlayerSwimming(playerID uint64) bool
	SetPlayerSwimming(playerID uint64, value bool) bool
	PlayerFlying(playerID uint64) bool
	SetPlayerFlying(playerID uint64, value bool) bool
	PlayerGliding(playerID uint64) bool
	SetPlayerGliding(playerID uint64, value bool) bool
	PlayerCrawling(playerID uint64) bool
	SetPlayerCrawling(playerID uint64, value bool) bool
	PlayerUsingItem(playerID uint64) bool
	PlayerInvisible(playerID uint64) bool
	SetPlayerInvisible(playerID uint64, value bool) bool
	PlayerImmobile(playerID uint64) bool
	SetPlayerImmobile(playerID uint64, value bool) bool
	PlayerDead(playerID uint64) bool
	SetPlayerOnFireMillis(playerID uint64, millis int64) bool
	AddPlayerFood(playerID uint64, points int32) bool
	PlayerUseItem(playerID uint64) bool
	PlayerJump(playerID uint64) bool
	PlayerSwingArm(playerID uint64) bool
	PlayerWake(playerID uint64) bool
	PlayerExtinguish(playerID uint64) bool
	SetPlayerShowCoordinates(playerID uint64, value bool) bool
	PlayerMainHandItem(playerID uint64) ItemStackData
	SetPlayerMainHandItem(playerID uint64, stack ItemStackData) bool
	PlayerOffHandItem(playerID uint64) ItemStackData
	SetPlayerOffHandItem(playerID uint64, stack ItemStackData) bool
	PlayerInventoryItems(playerID uint64) []ItemStackData
	SetPlayerInventoryItems(playerID uint64, items []ItemStackData) bool
	PlayerEnderChestItems(playerID uint64) []ItemStackData
	SetPlayerEnderChestItems(playerID uint64, items []ItemStackData) bool
	PlayerArmourItems(playerID uint64) []ItemStackData
	SetPlayerArmourItems(playerID uint64, items []ItemStackData) bool
	SetPlayerHeldSlot(playerID uint64, slot int32) bool
	PlayerMoveItemsToInventory(playerID uint64) bool
	PlayerCloseForm(playerID uint64) bool
	PlayerCloseDialogue(playerID uint64) bool
	PlayerSendMenuForm(playerID uint64, value MenuFormData) bool
	PlayerSendModalForm(playerID uint64, value ModalFormData) bool
	PlayerMessage(playerID uint64, message string)
}

func playerHealth(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerHealth(playerID) })
}

func setPlayerHealth(playerID uint64, health float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerHealth(playerID, health) })
}

func playerFood(playerID uint64) int32 {
	return hostValue(int32(0), func(h Host) int32 { return h.PlayerFood(playerID) })
}

func setPlayerFood(playerID uint64, food int32) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerFood(playerID, food) })
}

func playerName(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerName(playerID) })
}

func playerGameMode(playerID uint64) GameMode {
	return hostValue(GameMode(0), func(h Host) GameMode { return GameMode(h.PlayerGameMode(playerID)) })
}

func setPlayerGameMode(playerID uint64, mode GameMode) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerGameMode(playerID, int32(mode)) })
}

func playerXUID(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerXUID(playerID) })
}

func playerDeviceID(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerDeviceID(playerID) })
}

func playerDeviceModel(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerDeviceModel(playerID) })
}

func playerSelfSignedID(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerSelfSignedID(playerID) })
}

func playerNameTag(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerNameTag(playerID) })
}

func setPlayerNameTag(playerID uint64, value string) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerNameTag(playerID, value) })
}

func playerScoreTag(playerID uint64) string {
	return hostValue("", func(h Host) string { return h.PlayerScoreTag(playerID) })
}

func setPlayerScoreTag(playerID uint64, value string) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerScoreTag(playerID, value) })
}

func playerAbsorption(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerAbsorption(playerID) })
}

func setPlayerAbsorption(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerAbsorption(playerID, value) })
}

func playerMaxHealth(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerMaxHealth(playerID) })
}

func setPlayerMaxHealth(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerMaxHealth(playerID, value) })
}

func playerSpeed(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerSpeed(playerID) })
}

func setPlayerSpeed(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerSpeed(playerID, value) })
}

func playerFlightSpeed(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerFlightSpeed(playerID) })
}

func setPlayerFlightSpeed(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerFlightSpeed(playerID, value) })
}

func playerVerticalFlightSpeed(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerVerticalFlightSpeed(playerID) })
}

func setPlayerVerticalFlightSpeed(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerVerticalFlightSpeed(playerID, value) })
}

func playerExperience(playerID uint64) int32 {
	return hostValue(int32(0), func(h Host) int32 { return h.PlayerExperience(playerID) })
}

func playerExperienceLevel(playerID uint64) int32 {
	return hostValue(int32(0), func(h Host) int32 { return h.PlayerExperienceLevel(playerID) })
}

func setPlayerExperienceLevel(playerID uint64, value int32) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerExperienceLevel(playerID, value) })
}

func playerExperienceProgress(playerID uint64) float64 {
	return hostValue(float64(0), func(h Host) float64 { return h.PlayerExperienceProgress(playerID) })
}

func setPlayerExperienceProgress(playerID uint64, value float64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerExperienceProgress(playerID, value) })
}

func playerOnGround(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerOnGround(playerID) })
}

func playerSneaking(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerSneaking(playerID) })
}

func setPlayerSneaking(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerSneaking(playerID, value) })
}

func playerSprinting(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerSprinting(playerID) })
}

func setPlayerSprinting(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerSprinting(playerID, value) })
}

func playerSwimming(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerSwimming(playerID) })
}

func setPlayerSwimming(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerSwimming(playerID, value) })
}

func playerFlying(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerFlying(playerID) })
}

func setPlayerFlying(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerFlying(playerID, value) })
}

func playerGliding(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerGliding(playerID) })
}

func setPlayerGliding(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerGliding(playerID, value) })
}

func playerCrawling(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerCrawling(playerID) })
}

func setPlayerCrawling(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerCrawling(playerID, value) })
}

func playerUsingItem(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerUsingItem(playerID) })
}

func playerInvisible(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerInvisible(playerID) })
}

func setPlayerInvisible(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerInvisible(playerID, value) })
}

func playerImmobile(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerImmobile(playerID) })
}

func setPlayerImmobile(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerImmobile(playerID, value) })
}

func playerDead(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerDead(playerID) })
}

func setPlayerOnFireMillis(playerID uint64, millis int64) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerOnFireMillis(playerID, millis) })
}

func addPlayerFood(playerID uint64, points int32) bool {
	return hostBool(func(h Host) bool { return h.AddPlayerFood(playerID, points) })
}

func playerUseItem(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerUseItem(playerID) })
}

func playerJump(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerJump(playerID) })
}

func playerSwingArm(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerSwingArm(playerID) })
}

func playerWake(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerWake(playerID) })
}

func playerExtinguish(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerExtinguish(playerID) })
}

func setPlayerShowCoordinates(playerID uint64, value bool) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerShowCoordinates(playerID, value) })
}

func playerMainHandItem(playerID uint64) ItemStackData {
	return hostValue(ItemStackData{}, func(h Host) ItemStackData { return h.PlayerMainHandItem(playerID) })
}

func setPlayerMainHandItem(playerID uint64, stack ItemStackData) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerMainHandItem(playerID, stack) })
}

func playerOffHandItem(playerID uint64) ItemStackData {
	return hostValue(ItemStackData{}, func(h Host) ItemStackData { return h.PlayerOffHandItem(playerID) })
}

func setPlayerOffHandItem(playerID uint64, stack ItemStackData) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerOffHandItem(playerID, stack) })
}

func playerInventoryItems(playerID uint64) []ItemStackData {
	return hostValue(nil, func(h Host) []ItemStackData { return h.PlayerInventoryItems(playerID) })
}

func setPlayerInventoryItems(playerID uint64, items []ItemStackData) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerInventoryItems(playerID, items) })
}

func playerEnderChestItems(playerID uint64) []ItemStackData {
	return hostValue(nil, func(h Host) []ItemStackData { return h.PlayerEnderChestItems(playerID) })
}

func setPlayerEnderChestItems(playerID uint64, items []ItemStackData) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerEnderChestItems(playerID, items) })
}

func playerArmourItems(playerID uint64) []ItemStackData {
	return hostValue(nil, func(h Host) []ItemStackData { return h.PlayerArmourItems(playerID) })
}

func setPlayerArmourItems(playerID uint64, items []ItemStackData) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerArmourItems(playerID, items) })
}

func setPlayerHeldSlot(playerID uint64, slot int32) bool {
	return hostBool(func(h Host) bool { return h.SetPlayerHeldSlot(playerID, slot) })
}

func playerMoveItemsToInventory(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerMoveItemsToInventory(playerID) })
}

func playerCloseForm(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerCloseForm(playerID) })
}

func playerCloseDialogue(playerID uint64) bool {
	return hostBool(func(h Host) bool { return h.PlayerCloseDialogue(playerID) })
}

func playerSendMenuForm(playerID uint64, value MenuFormData) bool {
	return hostBool(func(h Host) bool { return h.PlayerSendMenuForm(playerID, value) })
}

func playerSendModalForm(playerID uint64, value ModalFormData) bool {
	return hostBool(func(h Host) bool { return h.PlayerSendModalForm(playerID, value) })
}

func playerMessage(playerID uint64, message string) {
	hostDo(func(h Host) { h.PlayerMessage(playerID, message) })
}
