// Code generated by go generate; DO NOT EDIT.
package guest

import "github.com/sandertv/gophertunnel/minecraft/text"

func (p PlayerRef) Health() float64 {
	return playerHealth(p.id)
}

func (p PlayerRef) SetHealth(health float64) bool {
	return setPlayerHealth(p.id, health)
}

func (p PlayerRef) Food() int32 {
	return playerFood(p.id)
}

func (p PlayerRef) SetFood(food int32) bool {
	return setPlayerFood(p.id, food)
}

func (p PlayerRef) Name() string {
	return playerName(p.id)
}

func (p PlayerRef) GameMode() GameMode {
	return playerGameMode(p.id)
}

func (p PlayerRef) SetGameMode(mode GameMode) bool {
	return setPlayerGameMode(p.id, mode)
}

func (p PlayerRef) XUID() string {
	return playerXUID(p.id)
}

func (p PlayerRef) DeviceID() string {
	return playerDeviceID(p.id)
}

func (p PlayerRef) DeviceModel() string {
	return playerDeviceModel(p.id)
}

func (p PlayerRef) SelfSignedID() string {
	return playerSelfSignedID(p.id)
}

func (p PlayerRef) NameTag() string {
	return playerNameTag(p.id)
}

func (p PlayerRef) SetNameTag(value string) bool {
	return setPlayerNameTag(p.id, value)
}

func (p PlayerRef) ScoreTag() string {
	return playerScoreTag(p.id)
}

func (p PlayerRef) SetScoreTag(value string) bool {
	return setPlayerScoreTag(p.id, value)
}

func (p PlayerRef) Absorption() float64 {
	return playerAbsorption(p.id)
}

func (p PlayerRef) SetAbsorption(value float64) bool {
	return setPlayerAbsorption(p.id, value)
}

func (p PlayerRef) MaxHealth() float64 {
	return playerMaxHealth(p.id)
}

func (p PlayerRef) SetMaxHealth(value float64) bool {
	return setPlayerMaxHealth(p.id, value)
}

func (p PlayerRef) Speed() float64 {
	return playerSpeed(p.id)
}

func (p PlayerRef) SetSpeed(value float64) bool {
	return setPlayerSpeed(p.id, value)
}

func (p PlayerRef) FlightSpeed() float64 {
	return playerFlightSpeed(p.id)
}

func (p PlayerRef) SetFlightSpeed(value float64) bool {
	return setPlayerFlightSpeed(p.id, value)
}

func (p PlayerRef) VerticalFlightSpeed() float64 {
	return playerVerticalFlightSpeed(p.id)
}

func (p PlayerRef) SetVerticalFlightSpeed(value float64) bool {
	return setPlayerVerticalFlightSpeed(p.id, value)
}

func (p PlayerRef) Experience() int32 {
	return playerExperience(p.id)
}

func (p PlayerRef) ExperienceLevel() int32 {
	return playerExperienceLevel(p.id)
}

func (p PlayerRef) SetExperienceLevel(value int32) bool {
	return setPlayerExperienceLevel(p.id, value)
}

func (p PlayerRef) ExperienceProgress() float64 {
	return playerExperienceProgress(p.id)
}

func (p PlayerRef) SetExperienceProgress(value float64) bool {
	return setPlayerExperienceProgress(p.id, value)
}

func (p PlayerRef) OnGround() bool {
	return playerOnGround(p.id)
}

func (p PlayerRef) Sneaking() bool {
	return playerSneaking(p.id)
}

func (p PlayerRef) SetSneaking(value bool) bool {
	return setPlayerSneaking(p.id, value)
}

func (p PlayerRef) Sprinting() bool {
	return playerSprinting(p.id)
}

func (p PlayerRef) SetSprinting(value bool) bool {
	return setPlayerSprinting(p.id, value)
}

func (p PlayerRef) Swimming() bool {
	return playerSwimming(p.id)
}

func (p PlayerRef) SetSwimming(value bool) bool {
	return setPlayerSwimming(p.id, value)
}

func (p PlayerRef) Flying() bool {
	return playerFlying(p.id)
}

func (p PlayerRef) SetFlying(value bool) bool {
	return setPlayerFlying(p.id, value)
}

func (p PlayerRef) Gliding() bool {
	return playerGliding(p.id)
}

func (p PlayerRef) SetGliding(value bool) bool {
	return setPlayerGliding(p.id, value)
}

func (p PlayerRef) Crawling() bool {
	return playerCrawling(p.id)
}

func (p PlayerRef) SetCrawling(value bool) bool {
	return setPlayerCrawling(p.id, value)
}

func (p PlayerRef) UsingItem() bool {
	return playerUsingItem(p.id)
}

func (p PlayerRef) Invisible() bool {
	return playerInvisible(p.id)
}

func (p PlayerRef) SetInvisible(value bool) bool {
	return setPlayerInvisible(p.id, value)
}

func (p PlayerRef) Immobile() bool {
	return playerImmobile(p.id)
}

func (p PlayerRef) SetImmobile(value bool) bool {
	return setPlayerImmobile(p.id, value)
}

func (p PlayerRef) Dead() bool {
	return playerDead(p.id)
}

func (p PlayerRef) SetOnFireMillis(millis int64) bool {
	return setPlayerOnFireMillis(p.id, millis)
}

func (p PlayerRef) AddFood(points int32) bool {
	return addPlayerFood(p.id, points)
}

func (p PlayerRef) UseItem() bool {
	return playerUseItem(p.id)
}

func (p PlayerRef) Jump() bool {
	return playerJump(p.id)
}

func (p PlayerRef) SwingArm() bool {
	return playerSwingArm(p.id)
}

func (p PlayerRef) Wake() bool {
	return playerWake(p.id)
}

func (p PlayerRef) Extinguish() bool {
	return playerExtinguish(p.id)
}

func (p PlayerRef) SetShowCoordinates(value bool) bool {
	return setPlayerShowCoordinates(p.id, value)
}

func (p PlayerRef) Message(message string) {
	playerMessage(p.id, message)
}

func (p PlayerRef) Messagef(format string, a ...any) {
	p.Message(text.Colourf(format, a...))
}
