// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	block "github.com/df-mc/dragonfly/server/block"
	world "github.com/df-mc/dragonfly/server/world"
	mgl64 "github.com/go-gl/mathgl/mgl64"
)

//export Block_ExplosionConfig_Ctor
func Block_ExplosionConfig_Ctor() C.uint64_t {
	value := &block.ExplosionConfig{}
	return registerObject(value)
}

//export Block_ExplosionConfig_Explode
func Block_ExplosionConfig_Explode(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*block.ExplosionConfig](self)
	obj.Explode(mustLoadHandle[*world.Tx](p1), mustLoadHandle[mgl64.Vec3](p2))
}
