// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	bossbar "github.com/df-mc/dragonfly/server/player/bossbar"
)

//export Bossbar_Colour_Ctor
func Bossbar_Colour_Ctor() C.uint64_t {
	value := &bossbar.Colour{}
	return registerObject(value)
}

//export Bossbar_Colour_Uint8
func Bossbar_Colour_Uint8(self C.uint64_t) C.uint8_t {
	obj := mustLoadHandle[*bossbar.Colour](self)
	out0 := obj.Uint8()
	ret0 := C.uint8_t(uint8(out0))
	return ret0
}
