// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	bossbar "github.com/df-mc/dragonfly/server/player/bossbar"
)

//export Bossbar_BossBar_Ctor
func Bossbar_BossBar_Ctor() C.uint64_t {
	value := &bossbar.BossBar{}
	return registerObject(value)
}

//export Bossbar_BossBar_Colour
func Bossbar_BossBar_Colour(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*bossbar.BossBar](self)
	out0 := obj.Colour()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Bossbar_BossBar_HealthPercentage
func Bossbar_BossBar_HealthPercentage(self C.uint64_t) C.double {
	obj := mustLoadHandle[*bossbar.BossBar](self)
	out0 := obj.HealthPercentage()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Bossbar_BossBar_Text
func Bossbar_BossBar_Text(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*bossbar.BossBar](self)
	out0 := obj.Text()
	ret0 := C.CString(out0)
	return ret0
}

//export Bossbar_BossBar_WithColour
func Bossbar_BossBar_WithColour(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*bossbar.BossBar](self)
	out0 := obj.WithColour(mustLoadStructValue[bossbar.Colour](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Bossbar_BossBar_WithHealthPercentage
func Bossbar_BossBar_WithHealthPercentage(self C.uint64_t, p1 C.double) C.uint64_t {
	obj := mustLoadHandle[*bossbar.BossBar](self)
	out0 := obj.WithHealthPercentage(float64(p1))
	ret0 := registerStructValue(out0)
	return ret0
}
