// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	chat "github.com/df-mc/dragonfly/server/player/chat"
	language "golang.org/x/text/language"
)

//export Chat_Translation_Ctor
func Chat_Translation_Ctor() C.uint64_t {
	value := &chat.Translation{}
	return registerObject(value)
}

//export Chat_Translation_Enc
func Chat_Translation_Enc(self C.uint64_t, p1 *C.char) C.uint64_t {
	obj := mustLoadHandle[*chat.Translation](self)
	out0 := obj.Enc(C.GoString(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Chat_Translation_F
func Chat_Translation_F(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*chat.Translation](self)
	out0 := obj.F(mustLoadHandle[[]interface{}](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Chat_Translation_Resolve
func Chat_Translation_Resolve(self C.uint64_t, p1 C.uint64_t) *C.char {
	obj := mustLoadHandle[*chat.Translation](self)
	out0 := obj.Resolve(mustLoadStructValue[language.Tag](p1))
	ret0 := C.CString(out0)
	return ret0
}

//export Chat_Translation_Zero
func Chat_Translation_Zero(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*chat.Translation](self)
	out0 := obj.Zero()
	ret0 := toCBool(out0)
	return ret0
}
