// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	cmd "github.com/df-mc/dragonfly/server/cmd"
	chat "github.com/df-mc/dragonfly/server/player/chat"
	"unsafe"
)

//export Cmd_Output_Ctor
func Cmd_Output_Ctor() C.uint64_t {
	value := &cmd.Output{}
	return registerObject(value)
}

//export Cmd_Output_Error
func Cmd_Output_Error(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Error(mustLoadHandle[[]interface{}](p1)...)
}

//export Cmd_Output_ErrorCount
func Cmd_Output_ErrorCount(self C.uint64_t) C.int {
	obj := mustLoadHandle[*cmd.Output](self)
	out0 := obj.ErrorCount()
	ret0 := C.int(int(out0))
	return ret0
}

//export Cmd_Output_Errorf
func Cmd_Output_Errorf(self C.uint64_t, p1 *C.char, p2 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Errorf(C.GoString(p1), mustLoadHandle[[]interface{}](p2)...)
}

//export Cmd_Output_Errors
func Cmd_Output_Errors(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*cmd.Output](self)
	out0 := obj.Errors()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Cmd_Output_Errort
func Cmd_Output_Errort(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Errort(mustLoadStructValue[chat.Translation](p1), mustLoadHandle[[]interface{}](p2)...)
}

//export Cmd_Output_MessageCount
func Cmd_Output_MessageCount(self C.uint64_t) C.int {
	obj := mustLoadHandle[*cmd.Output](self)
	out0 := obj.MessageCount()
	ret0 := C.int(int(out0))
	return ret0
}

//export Cmd_Output_Messages
func Cmd_Output_Messages(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*cmd.Output](self)
	out0 := obj.Messages()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Cmd_Output_Print
func Cmd_Output_Print(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Print(mustLoadHandle[[]interface{}](p1)...)
}

//export Cmd_Output_Printf
func Cmd_Output_Printf(self C.uint64_t, p1 *C.char, p2 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Printf(C.GoString(p1), mustLoadHandle[[]interface{}](p2)...)
}

//export Cmd_Output_Printt
func Cmd_Output_Printt(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*cmd.Output](self)
	obj.Printt(mustLoadStructValue[chat.Translation](p1), mustLoadHandle[[]interface{}](p2)...)
}
