// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	color "image/color"
)

//export Color_RGBA64_Ctor
func Color_RGBA64_Ctor() C.uint64_t {
	value := &color.RGBA64{}
	return registerObject(value)
}

//export Color_RGBA64_RGBA
func Color_RGBA64_RGBA(self C.uint64_t) C.Color_RGBA64_RGBA_Result {
	obj := mustLoadHandle[*color.RGBA64](self)
	out0, out1, out2, out3 := obj.RGBA()
	v0 := C.uint32_t(uint32(out0))
	v1 := C.uint32_t(uint32(out1))
	v2 := C.uint32_t(uint32(out2))
	v3 := C.uint32_t(uint32(out3))
	return C.Color_RGBA64_RGBA_Result{
		v0: v0,
		v1: v1,
		v2: v2,
		v3: v3,
	}
}
