// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	cube "github.com/df-mc/dragonfly/server/block/cube"
	mgl64 "github.com/go-gl/mathgl/mgl64"
	"unsafe"
)

//export Cube_BBox_Ctor
func Cube_BBox_Ctor() C.uint64_t {
	value := &cube.BBox{}
	return registerObject(value)
}

//export Cube_BBox_Corners
func Cube_BBox_Corners(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Corners()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Cube_BBox_Extend
func Cube_BBox_Extend(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Extend(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_ExtendTowards
func Cube_BBox_ExtendTowards(self C.uint64_t, p1 C.int, p2 C.double) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.ExtendTowards(cube.Face(int(p1)), float64(p2))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_Grow
func Cube_BBox_Grow(self C.uint64_t, p1 C.double) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Grow(float64(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_GrowVec3
func Cube_BBox_GrowVec3(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.GrowVec3(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_Height
func Cube_BBox_Height(self C.uint64_t) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Height()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_IntersectsWith
func Cube_BBox_IntersectsWith(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.IntersectsWith(mustLoadStructValue[cube.BBox](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Cube_BBox_Length
func Cube_BBox_Length(self C.uint64_t) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Length()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_Max
func Cube_BBox_Max(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Max()
	ret0Slice := out0[:]
	var ret0ElemZero C.double
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.double(float64(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Cube_BBox_Min
func Cube_BBox_Min(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Min()
	ret0Slice := out0[:]
	var ret0ElemZero C.double
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.double(float64(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Cube_BBox_Mul
func Cube_BBox_Mul(self C.uint64_t, p1 C.double) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Mul(float64(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_Stretch
func Cube_BBox_Stretch(self C.uint64_t, p1 C.int, p2 C.double) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Stretch(cube.Axis(int(p1)), float64(p2))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_Translate
func Cube_BBox_Translate(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Translate(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_TranslateTowards
func Cube_BBox_TranslateTowards(self C.uint64_t, p1 C.int, p2 C.double) C.uint64_t {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.TranslateTowards(cube.Face(int(p1)), float64(p2))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Cube_BBox_Vec3Within
func Cube_BBox_Vec3Within(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Vec3Within(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Cube_BBox_Vec3WithinXY
func Cube_BBox_Vec3WithinXY(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Vec3WithinXY(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Cube_BBox_Vec3WithinXZ
func Cube_BBox_Vec3WithinXZ(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Vec3WithinXZ(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Cube_BBox_Vec3WithinYZ
func Cube_BBox_Vec3WithinYZ(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Vec3WithinYZ(mustLoadHandle[mgl64.Vec3](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Cube_BBox_Volume
func Cube_BBox_Volume(self C.uint64_t) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Volume()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_Width
func Cube_BBox_Width(self C.uint64_t) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.Width()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_XOffset
func Cube_BBox_XOffset(self C.uint64_t, p1 C.uint64_t, p2 C.double) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.XOffset(mustLoadStructValue[cube.BBox](p1), float64(p2))
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_YOffset
func Cube_BBox_YOffset(self C.uint64_t, p1 C.uint64_t, p2 C.double) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.YOffset(mustLoadStructValue[cube.BBox](p1), float64(p2))
	ret0 := C.double(float64(out0))
	return ret0
}

//export Cube_BBox_ZOffset
func Cube_BBox_ZOffset(self C.uint64_t, p1 C.uint64_t, p2 C.double) C.double {
	obj := mustLoadHandle[*cube.BBox](self)
	out0 := obj.ZOffset(mustLoadStructValue[cube.BBox](p1), float64(p2))
	ret0 := C.double(float64(out0))
	return ret0
}
