// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	dialogue "github.com/df-mc/dragonfly/server/player/dialogue"
	"unsafe"
)

//export Dialogue_DisplaySettings_Ctor
func Dialogue_DisplaySettings_Ctor() C.uint64_t {
	value := &dialogue.DisplaySettings{}
	return registerObject(value)
}

//export Dialogue_DisplaySettings_MarshalJSON
func Dialogue_DisplaySettings_MarshalJSON(self C.uint64_t) C.Dialogue_DisplaySettings_MarshalJSON_Result {
	obj := mustLoadHandle[*dialogue.DisplaySettings](self)
	out0, out1 := obj.MarshalJSON()
	var v0ElemZero C.uint8_t
	v0ElemSize := C.int(unsafe.Sizeof(v0ElemZero))
	v0 := C.GoArray{data: nil, length: 0, elementSize: v0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(v0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint8_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.uint8_t(uint8(out0[i]))
			}
			v0.data = data
			v0.length = C.int(len(out0))
		}
	}
	v1 := registerObject(out1)
	return C.Dialogue_DisplaySettings_MarshalJSON_Result{
		v0: v0,
		v1: v1,
	}
}
