// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	dialogue "github.com/df-mc/dragonfly/server/player/dialogue"
	world "github.com/df-mc/dragonfly/server/world"
	"unsafe"
)

//export Dialogue_Dialogue_Ctor
func Dialogue_Dialogue_Ctor() C.uint64_t {
	value := &dialogue.Dialogue{}
	return registerObject(value)
}

//export Dialogue_Dialogue_Body
func Dialogue_Dialogue_Body(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.Body()
	ret0 := C.CString(out0)
	return ret0
}

//export Dialogue_Dialogue_Buttons
func Dialogue_Dialogue_Buttons(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.Buttons()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Dialogue_Dialogue_Close
func Dialogue_Dialogue_Close(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	obj.Close(mustLoadHandle[dialogue.Submitter](p1), mustLoadHandle[*world.Tx](p2))
}

//export Dialogue_Dialogue_Display
func Dialogue_Dialogue_Display(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.Display()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Dialogue_Dialogue_MarshalJSON
func Dialogue_Dialogue_MarshalJSON(self C.uint64_t) C.Dialogue_Dialogue_MarshalJSON_Result {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0, out1 := obj.MarshalJSON()
	var v0ElemZero C.uint8_t
	v0ElemSize := C.int(unsafe.Sizeof(v0ElemZero))
	v0 := C.GoArray{data: nil, length: 0, elementSize: v0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(v0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint8_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.uint8_t(uint8(out0[i]))
			}
			v0.data = data
			v0.length = C.int(len(out0))
		}
	}
	v1 := registerObject(out1)
	return C.Dialogue_Dialogue_MarshalJSON_Result{
		v0: v0,
		v1: v1,
	}
}

//export Dialogue_Dialogue_Submit
func Dialogue_Dialogue_Submit(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t, p3 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.Submit(uint(p1), mustLoadHandle[dialogue.Submitter](p2), mustLoadHandle[*world.Tx](p3))
	ret0 := registerObject(out0)
	return ret0
}

//export Dialogue_Dialogue_Title
func Dialogue_Dialogue_Title(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.Title()
	ret0 := C.CString(out0)
	return ret0
}

//export Dialogue_Dialogue_WithBody
func Dialogue_Dialogue_WithBody(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.WithBody(mustLoadHandle[[]interface{}](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Dialogue_Dialogue_WithButtons
func Dialogue_Dialogue_WithButtons(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.WithButtons(mustLoadHandle[[]dialogue.Button](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Dialogue_Dialogue_WithDisplay
func Dialogue_Dialogue_WithDisplay(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*dialogue.Dialogue](self)
	out0 := obj.WithDisplay(mustLoadStructValue[dialogue.DisplaySettings](p1))
	ret0 := registerStructValue(out0)
	return ret0
}
