// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	effect "github.com/df-mc/dragonfly/server/entity/effect"
)

//export Effect_Effect_Ctor
func Effect_Effect_Ctor() C.uint64_t {
	value := &effect.Effect{}
	return registerObject(value)
}

//export Effect_Effect_Ambient
func Effect_Effect_Ambient(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Ambient()
	ret0 := toCBool(out0)
	return ret0
}

//export Effect_Effect_Duration
func Effect_Effect_Duration(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Duration()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Effect_Effect_Infinite
func Effect_Effect_Infinite(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Infinite()
	ret0 := toCBool(out0)
	return ret0
}

//export Effect_Effect_Level
func Effect_Effect_Level(self C.uint64_t) C.int {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Level()
	ret0 := C.int(int(out0))
	return ret0
}

//export Effect_Effect_ParticlesHidden
func Effect_Effect_ParticlesHidden(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.ParticlesHidden()
	ret0 := toCBool(out0)
	return ret0
}

//export Effect_Effect_Tick
func Effect_Effect_Tick(self C.uint64_t) C.int {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Tick()
	ret0 := C.int(int(out0))
	return ret0
}

//export Effect_Effect_TickDuration
func Effect_Effect_TickDuration(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.TickDuration()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Effect_Effect_Type
func Effect_Effect_Type(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.Type()
	ret0 := registerObject(out0)
	return ret0
}

//export Effect_Effect_WithoutParticles
func Effect_Effect_WithoutParticles(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*effect.Effect](self)
	out0 := obj.WithoutParticles()
	ret0 := registerStructValue(out0)
	return ret0
}
