// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	hud "github.com/df-mc/dragonfly/server/player/hud"
)

//export Hud_Element_Ctor
func Hud_Element_Ctor() C.uint64_t {
	value := &hud.Element{}
	return registerObject(value)
}

//export Hud_Element_Uint8
func Hud_Element_Uint8(self C.uint64_t) C.uint8_t {
	obj := mustLoadHandle[*hud.Element](self)
	out0 := obj.Uint8()
	ret0 := C.uint8_t(uint8(out0))
	return ret0
}
