// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	image "image"
)

//export Image_Point_Ctor
func Image_Point_Ctor() C.uint64_t {
	value := &image.Point{}
	return registerObject(value)
}

//export Image_Point_Add
func Image_Point_Add(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Add(mustLoadStructValue[image.Point](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Point_Div
func Image_Point_Div(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Div(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Point_Eq
func Image_Point_Eq(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Eq(mustLoadStructValue[image.Point](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Point_In
func Image_Point_In(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.In(mustLoadStructValue[image.Rectangle](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Point_Mod
func Image_Point_Mod(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Mod(mustLoadStructValue[image.Rectangle](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Point_Mul
func Image_Point_Mul(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Mul(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Point_String
func Image_Point_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Image_Point_Sub
func Image_Point_Sub(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Point](self)
	out0 := obj.Sub(mustLoadStructValue[image.Point](p1))
	ret0 := registerStructValue(out0)
	return ret0
}
