// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	image "image"
)

//export Image_Rectangle_Ctor
func Image_Rectangle_Ctor() C.uint64_t {
	value := &image.Rectangle{}
	return registerObject(value)
}

//export Image_Rectangle_Add
func Image_Rectangle_Add(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Add(mustLoadStructValue[image.Point](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_At
func Image_Rectangle_At(self C.uint64_t, p1 C.int, p2 C.int) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.At(int(p1), int(p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Image_Rectangle_Bounds
func Image_Rectangle_Bounds(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Bounds()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_Canon
func Image_Rectangle_Canon(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Canon()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_ColorModel
func Image_Rectangle_ColorModel(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.ColorModel()
	ret0 := registerObject(out0)
	return ret0
}

//export Image_Rectangle_Dx
func Image_Rectangle_Dx(self C.uint64_t) C.int {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Dx()
	ret0 := C.int(int(out0))
	return ret0
}

//export Image_Rectangle_Dy
func Image_Rectangle_Dy(self C.uint64_t) C.int {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Dy()
	ret0 := C.int(int(out0))
	return ret0
}

//export Image_Rectangle_Empty
func Image_Rectangle_Empty(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Empty()
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Rectangle_Eq
func Image_Rectangle_Eq(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Eq(mustLoadStructValue[image.Rectangle](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Rectangle_In
func Image_Rectangle_In(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.In(mustLoadStructValue[image.Rectangle](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Rectangle_Inset
func Image_Rectangle_Inset(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Inset(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_Intersect
func Image_Rectangle_Intersect(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Intersect(mustLoadStructValue[image.Rectangle](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_Overlaps
func Image_Rectangle_Overlaps(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Overlaps(mustLoadStructValue[image.Rectangle](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Image_Rectangle_RGBA64At
func Image_Rectangle_RGBA64At(self C.uint64_t, p1 C.int, p2 C.int) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.RGBA64At(int(p1), int(p2))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_Size
func Image_Rectangle_Size(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Size()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_String
func Image_Rectangle_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Image_Rectangle_Sub
func Image_Rectangle_Sub(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Sub(mustLoadStructValue[image.Point](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Image_Rectangle_Union
func Image_Rectangle_Union(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*image.Rectangle](self)
	out0 := obj.Union(mustLoadStructValue[image.Rectangle](p1))
	ret0 := registerStructValue(out0)
	return ret0
}
