// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	item "github.com/df-mc/dragonfly/server/item"
	inventory "github.com/df-mc/dragonfly/server/item/inventory"
	world "github.com/df-mc/dragonfly/server/world"
	"unsafe"
)

//export Inventory_Armour_Ctor
func Inventory_Armour_Ctor() C.uint64_t {
	value := &inventory.Armour{}
	return registerObject(value)
}

//export Inventory_Armour_Boots
func Inventory_Armour_Boots(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Boots()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Inventory_Armour_Chestplate
func Inventory_Armour_Chestplate(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Chestplate()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Inventory_Armour_Clear
func Inventory_Armour_Clear(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Clear()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Armour_Close
func Inventory_Armour_Close(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Close()
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Armour_Damage
func Inventory_Armour_Damage(self C.uint64_t, p1 C.double, p2 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.Damage(float64(p1), mustLoadHandle[inventory.DamageFunc](p2))
}

//export Inventory_Armour_DamageReduction
func Inventory_Armour_DamageReduction(self C.uint64_t, p1 C.double, p2 C.uint64_t) C.double {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.DamageReduction(float64(p1), mustLoadHandle[world.DamageSource](p2))
	ret0 := C.double(float64(out0))
	return ret0
}

//export Inventory_Armour_Handle
func Inventory_Armour_Handle(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.Handle(mustLoadHandle[inventory.Handler](p1))
}

//export Inventory_Armour_Helmet
func Inventory_Armour_Helmet(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Helmet()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Inventory_Armour_HighestEnchantmentLevel
func Inventory_Armour_HighestEnchantmentLevel(self C.uint64_t, p1 C.uint64_t) C.int {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.HighestEnchantmentLevel(mustLoadHandle[item.EnchantmentType](p1))
	ret0 := C.int(int(out0))
	return ret0
}

//export Inventory_Armour_Inventory
func Inventory_Armour_Inventory(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Inventory()
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Armour_Items
func Inventory_Armour_Items(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Items()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Armour_KnockBackResistance
func Inventory_Armour_KnockBackResistance(self C.uint64_t) C.double {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.KnockBackResistance()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Inventory_Armour_Leggings
func Inventory_Armour_Leggings(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Leggings()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Inventory_Armour_Set
func Inventory_Armour_Set(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t, p3 C.uint64_t, p4 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.Set(mustLoadStructValue[item.Stack](p1), mustLoadStructValue[item.Stack](p2), mustLoadStructValue[item.Stack](p3), mustLoadStructValue[item.Stack](p4))
}

//export Inventory_Armour_SetBoots
func Inventory_Armour_SetBoots(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.SetBoots(mustLoadStructValue[item.Stack](p1))
}

//export Inventory_Armour_SetChestplate
func Inventory_Armour_SetChestplate(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.SetChestplate(mustLoadStructValue[item.Stack](p1))
}

//export Inventory_Armour_SetHelmet
func Inventory_Armour_SetHelmet(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.SetHelmet(mustLoadStructValue[item.Stack](p1))
}

//export Inventory_Armour_SetLeggings
func Inventory_Armour_SetLeggings(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Armour](self)
	obj.SetLeggings(mustLoadStructValue[item.Stack](p1))
}

//export Inventory_Armour_Slots
func Inventory_Armour_Slots(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.Slots()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Armour_String
func Inventory_Armour_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Inventory_Armour_ThornsDamage
func Inventory_Armour_ThornsDamage(self C.uint64_t, p1 C.uint64_t) C.double {
	obj := mustLoadHandle[*inventory.Armour](self)
	out0 := obj.ThornsDamage(mustLoadHandle[inventory.DamageFunc](p1))
	ret0 := C.double(float64(out0))
	return ret0
}
