// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	item "github.com/df-mc/dragonfly/server/item"
	inventory "github.com/df-mc/dragonfly/server/item/inventory"
	"unsafe"
)

//export Inventory_Inventory_Ctor
func Inventory_Inventory_Ctor() C.uint64_t {
	value := &inventory.Inventory{}
	return registerObject(value)
}

//export Inventory_Inventory_AddItem
func Inventory_Inventory_AddItem(self C.uint64_t, p1 C.uint64_t) C.Inventory_Inventory_AddItem_Result {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0, out1 := obj.AddItem(mustLoadStructValue[item.Stack](p1))
	v0 := C.int(int(out0))
	v1 := registerObject(out1)
	return C.Inventory_Inventory_AddItem_Result{
		v0: v0,
		v1: v1,
	}
}

//export Inventory_Inventory_Clear
func Inventory_Inventory_Clear(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Clear()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Inventory_Clone
func Inventory_Inventory_Clone(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Clone(mustLoadHandle[inventory.SlotFunc](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_Close
func Inventory_Inventory_Close(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Close()
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_ContainsItem
func Inventory_Inventory_ContainsItem(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.ContainsItem(mustLoadStructValue[item.Stack](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Inventory_Inventory_ContainsItemFunc
func Inventory_Inventory_ContainsItemFunc(self C.uint64_t, p1 C.int, p2 C.uint64_t) C.bool {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.ContainsItemFunc(int(p1), mustLoadHandle[func(item.Stack) bool](p2))
	ret0 := toCBool(out0)
	return ret0
}

//export Inventory_Inventory_Empty
func Inventory_Inventory_Empty(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Empty()
	ret0 := toCBool(out0)
	return ret0
}

//export Inventory_Inventory_First
func Inventory_Inventory_First(self C.uint64_t, p1 C.uint64_t) C.Inventory_Inventory_First_Result {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0, out1 := obj.First(mustLoadStructValue[item.Stack](p1))
	v0 := C.int(int(out0))
	v1 := toCBool(out1)
	return C.Inventory_Inventory_First_Result{
		v0: v0,
		v1: v1,
	}
}

//export Inventory_Inventory_FirstEmpty
func Inventory_Inventory_FirstEmpty(self C.uint64_t) C.Inventory_Inventory_FirstEmpty_Result {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0, out1 := obj.FirstEmpty()
	v0 := C.int(int(out0))
	v1 := toCBool(out1)
	return C.Inventory_Inventory_FirstEmpty_Result{
		v0: v0,
		v1: v1,
	}
}

//export Inventory_Inventory_FirstFunc
func Inventory_Inventory_FirstFunc(self C.uint64_t, p1 C.uint64_t) C.Inventory_Inventory_FirstFunc_Result {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0, out1 := obj.FirstFunc(mustLoadHandle[func(item.Stack) bool](p1))
	v0 := C.int(int(out0))
	v1 := toCBool(out1)
	return C.Inventory_Inventory_FirstFunc_Result{
		v0: v0,
		v1: v1,
	}
}

//export Inventory_Inventory_Handle
func Inventory_Inventory_Handle(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Inventory](self)
	obj.Handle(mustLoadHandle[inventory.Handler](p1))
}

//export Inventory_Inventory_Handler
func Inventory_Inventory_Handler(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Handler()
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_Item
func Inventory_Inventory_Item(self C.uint64_t, p1 C.int) C.Inventory_Inventory_Item_Result {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0, out1 := obj.Item(int(p1))
	v0 := registerStructValue(out0)
	v1 := registerObject(out1)
	return C.Inventory_Inventory_Item_Result{
		v0: v0,
		v1: v1,
	}
}

//export Inventory_Inventory_Items
func Inventory_Inventory_Items(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Items()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Inventory_Merge
func Inventory_Inventory_Merge(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Merge(mustLoadHandle[*inventory.Inventory](p1), mustLoadHandle[func(int, item.Stack, item.Stack)](p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_RemoveItem
func Inventory_Inventory_RemoveItem(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.RemoveItem(mustLoadStructValue[item.Stack](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_RemoveItemFunc
func Inventory_Inventory_RemoveItemFunc(self C.uint64_t, p1 C.int, p2 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.RemoveItemFunc(int(p1), mustLoadHandle[func(item.Stack) bool](p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_SetItem
func Inventory_Inventory_SetItem(self C.uint64_t, p1 C.int, p2 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.SetItem(int(p1), mustLoadStructValue[item.Stack](p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Inventory_Inventory_Size
func Inventory_Inventory_Size(self C.uint64_t) C.int {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Size()
	ret0 := C.int(int(out0))
	return ret0
}

//export Inventory_Inventory_SlotFunc
func Inventory_Inventory_SlotFunc(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Inventory](self)
	obj.SlotFunc(mustLoadHandle[inventory.SlotFunc](p1))
}

//export Inventory_Inventory_SlotValidatorFunc
func Inventory_Inventory_SlotValidatorFunc(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*inventory.Inventory](self)
	obj.SlotValidatorFunc(mustLoadHandle[inventory.SlotValidatorFunc](p1))
}

//export Inventory_Inventory_Slots
func Inventory_Inventory_Slots(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Slots()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Inventory_Inventory_String
func Inventory_Inventory_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Inventory_Inventory_Swap
func Inventory_Inventory_Swap(self C.uint64_t, p1 C.int, p2 C.int) C.uint64_t {
	obj := mustLoadHandle[*inventory.Inventory](self)
	out0 := obj.Swap(int(p1), int(p2))
	ret0 := registerObject(out0)
	return ret0
}
