// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	item "github.com/df-mc/dragonfly/server/item"
)

//export Item_UseContext_Ctor
func Item_UseContext_Ctor() C.uint64_t {
	value := &item.UseContext{}
	return registerObject(value)
}

//export Item_UseContext_Consume
func Item_UseContext_Consume(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*item.UseContext](self)
	obj.Consume(mustLoadStructValue[item.Stack](p1))
}

//export Item_UseContext_DamageItem
func Item_UseContext_DamageItem(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*item.UseContext](self)
	obj.DamageItem(int(p1))
}

//export Item_UseContext_SubtractFromCount
func Item_UseContext_SubtractFromCount(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*item.UseContext](self)
	obj.SubtractFromCount(int(p1))
}
