// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	item "github.com/df-mc/dragonfly/server/item"
	world "github.com/df-mc/dragonfly/server/world"
	"unsafe"
)

//export Item_Stack_Ctor
func Item_Stack_Ctor() C.uint64_t {
	value := &item.Stack{}
	return registerObject(value)
}

//export Item_Stack_AddStack
func Item_Stack_AddStack(self C.uint64_t, p1 C.uint64_t) C.Item_Stack_AddStack_Result {
	obj := mustLoadHandle[*item.Stack](self)
	out0, out1 := obj.AddStack(mustLoadStructValue[item.Stack](p1))
	v0 := registerStructValue(out0)
	v1 := registerStructValue(out1)
	return C.Item_Stack_AddStack_Result{
		v0: v0,
		v1: v1,
	}
}

//export Item_Stack_AnvilCost
func Item_Stack_AnvilCost(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.AnvilCost()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Stack_AsBreakable
func Item_Stack_AsBreakable(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.AsBreakable()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_AsUnbreakable
func Item_Stack_AsUnbreakable(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.AsUnbreakable()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_AttackDamage
func Item_Stack_AttackDamage(self C.uint64_t) C.double {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.AttackDamage()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Item_Stack_Comparable
func Item_Stack_Comparable(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Comparable(mustLoadStructValue[item.Stack](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Item_Stack_Count
func Item_Stack_Count(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Count()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Stack_CustomName
func Item_Stack_CustomName(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.CustomName()
	ret0 := C.CString(out0)
	return ret0
}

//export Item_Stack_Damage
func Item_Stack_Damage(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Damage(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_Durability
func Item_Stack_Durability(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Durability()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Stack_Empty
func Item_Stack_Empty(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Empty()
	ret0 := toCBool(out0)
	return ret0
}

//export Item_Stack_Enchantment
func Item_Stack_Enchantment(self C.uint64_t, p1 C.uint64_t) C.Item_Stack_Enchantment_Result {
	obj := mustLoadHandle[*item.Stack](self)
	out0, out1 := obj.Enchantment(mustLoadHandle[item.EnchantmentType](p1))
	v0 := registerStructValue(out0)
	v1 := toCBool(out1)
	return C.Item_Stack_Enchantment_Result{
		v0: v0,
		v1: v1,
	}
}

//export Item_Stack_Enchantments
func Item_Stack_Enchantments(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Enchantments()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Item_Stack_Equal
func Item_Stack_Equal(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Equal(mustLoadStructValue[item.Stack](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Item_Stack_Grow
func Item_Stack_Grow(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Grow(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_Item
func Item_Stack_Item(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Item()
	ret0 := registerObject(out0)
	return ret0
}

//export Item_Stack_Lore
func Item_Stack_Lore(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Lore()
	var ret0ElemZero *C.char
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((**C.char)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.CString(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Item_Stack_MaxCount
func Item_Stack_MaxCount(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.MaxCount()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Stack_MaxDurability
func Item_Stack_MaxDurability(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.MaxDurability()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Stack_String
func Item_Stack_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Item_Stack_Unbreakable
func Item_Stack_Unbreakable(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Unbreakable()
	ret0 := toCBool(out0)
	return ret0
}

//export Item_Stack_Value
func Item_Stack_Value(self C.uint64_t, p1 *C.char) C.Item_Stack_Value_Result {
	obj := mustLoadHandle[*item.Stack](self)
	out0, out1 := obj.Value(C.GoString(p1))
	v0 := registerObject(out0)
	v1 := toCBool(out1)
	return C.Item_Stack_Value_Result{
		v0: v0,
		v1: v1,
	}
}

//export Item_Stack_Values
func Item_Stack_Values(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.Values()
	ret0 := registerObject(out0)
	return ret0
}

//export Item_Stack_WithAnvilCost
func Item_Stack_WithAnvilCost(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithAnvilCost(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithCustomName
func Item_Stack_WithCustomName(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithCustomName(mustLoadHandle[[]interface{}](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithDurability
func Item_Stack_WithDurability(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithDurability(int(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithEnchantments
func Item_Stack_WithEnchantments(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithEnchantments(mustLoadHandle[[]item.Enchantment](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithItem
func Item_Stack_WithItem(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithItem(mustLoadHandle[world.Item](p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithLore
func Item_Stack_WithLore(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithLore(mustLoadHandle[[]string](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithValue
func Item_Stack_WithValue(self C.uint64_t, p1 *C.char, p2 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithValue(C.GoString(p1), mustLoadHandle[interface{}](p2))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Item_Stack_WithoutEnchantments
func Item_Stack_WithoutEnchantments(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Stack](self)
	out0 := obj.WithoutEnchantments(mustLoadHandle[[]item.EnchantmentType](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}
