// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	item "github.com/df-mc/dragonfly/server/item"
)

//export Item_Enchantment_Ctor
func Item_Enchantment_Ctor() C.uint64_t {
	value := &item.Enchantment{}
	return registerObject(value)
}

//export Item_Enchantment_Level
func Item_Enchantment_Level(self C.uint64_t) C.int {
	obj := mustLoadHandle[*item.Enchantment](self)
	out0 := obj.Level()
	ret0 := C.int(int(out0))
	return ret0
}

//export Item_Enchantment_Type
func Item_Enchantment_Type(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*item.Enchantment](self)
	out0 := obj.Type()
	ret0 := registerObject(out0)
	return ret0
}
