// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
	"unsafe"
)

//export Language_Tag_Ctor
func Language_Tag_Ctor() C.uint64_t {
	value := &language.Tag{}
	return registerObject(value)
}

//export Language_Tag_Base
func Language_Tag_Base(self C.uint64_t) C.Language_Tag_Base_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.Base()
	v0 := registerStructValue(out0)
	v1 := C.int(int(out1))
	return C.Language_Tag_Base_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_Extension
func Language_Tag_Extension(self C.uint64_t, p1 C.uint8_t) C.Language_Tag_Extension_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.Extension(uint8(p1))
	v0 := registerStructValue(out0)
	v1 := toCBool(out1)
	return C.Language_Tag_Extension_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_Extensions
func Language_Tag_Extensions(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.Extensions()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Language_Tag_IsRoot
func Language_Tag_IsRoot(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.IsRoot()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Tag_MarshalText
func Language_Tag_MarshalText(self C.uint64_t) C.Language_Tag_MarshalText_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.MarshalText()
	var v0ElemZero C.uint8_t
	v0ElemSize := C.int(unsafe.Sizeof(v0ElemZero))
	v0 := C.GoArray{data: nil, length: 0, elementSize: v0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(v0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint8_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.uint8_t(uint8(out0[i]))
			}
			v0.data = data
			v0.length = C.int(len(out0))
		}
	}
	v1 := registerObject(out1)
	return C.Language_Tag_MarshalText_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_Parent
func Language_Tag_Parent(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.Parent()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Language_Tag_Raw
func Language_Tag_Raw(self C.uint64_t) C.Language_Tag_Raw_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1, out2 := obj.Raw()
	v0 := registerStructValue(out0)
	v1 := registerStructValue(out1)
	v2 := registerStructValue(out2)
	return C.Language_Tag_Raw_Result{
		v0: v0,
		v1: v1,
		v2: v2,
	}
}

//export Language_Tag_Region
func Language_Tag_Region(self C.uint64_t) C.Language_Tag_Region_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.Region()
	v0 := registerStructValue(out0)
	v1 := C.int(int(out1))
	return C.Language_Tag_Region_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_Script
func Language_Tag_Script(self C.uint64_t) C.Language_Tag_Script_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.Script()
	v0 := registerStructValue(out0)
	v1 := C.int(int(out1))
	return C.Language_Tag_Script_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_SetTypeForKey
func Language_Tag_SetTypeForKey(self C.uint64_t, p1 *C.char, p2 *C.char) C.Language_Tag_SetTypeForKey_Result {
	obj := mustLoadHandle[*language.Tag](self)
	out0, out1 := obj.SetTypeForKey(C.GoString(p1), C.GoString(p2))
	v0 := registerStructValue(out0)
	v1 := registerObject(out1)
	return C.Language_Tag_SetTypeForKey_Result{
		v0: v0,
		v1: v1,
	}
}

//export Language_Tag_String
func Language_Tag_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Tag_TypeForKey
func Language_Tag_TypeForKey(self C.uint64_t, p1 *C.char) *C.char {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.TypeForKey(C.GoString(p1))
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Tag_UnmarshalText
func Language_Tag_UnmarshalText(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.UnmarshalText(mustLoadHandle[[]uint8](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export Language_Tag_Variants
func Language_Tag_Variants(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*language.Tag](self)
	out0 := obj.Variants()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}
