// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
)

//export Language_Variant_Ctor
func Language_Variant_Ctor() C.uint64_t {
	value := &language.Variant{}
	return registerObject(value)
}

//export Language_Variant_String
func Language_Variant_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Variant](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}
