// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
)

//export Language_Base_Ctor
func Language_Base_Ctor() C.uint64_t {
	value := &language.Base{}
	return registerObject(value)
}

//export Language_Base_ISO3
func Language_Base_ISO3(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Base](self)
	out0 := obj.ISO3()
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Base_IsPrivateUse
func Language_Base_IsPrivateUse(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Base](self)
	out0 := obj.IsPrivateUse()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Base_String
func Language_Base_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Base](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}
