// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
)

//export Language_Region_Ctor
func Language_Region_Ctor() C.uint64_t {
	value := &language.Region{}
	return registerObject(value)
}

//export Language_Region_Canonicalize
func Language_Region_Canonicalize(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.Canonicalize()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Language_Region_Contains
func Language_Region_Contains(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.Contains(mustLoadStructValue[language.Region](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Region_ISO3
func Language_Region_ISO3(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.ISO3()
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Region_IsCountry
func Language_Region_IsCountry(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.IsCountry()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Region_IsGroup
func Language_Region_IsGroup(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.IsGroup()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Region_IsPrivateUse
func Language_Region_IsPrivateUse(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.IsPrivateUse()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Region_M49
func Language_Region_M49(self C.uint64_t) C.int {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.M49()
	ret0 := C.int(int(out0))
	return ret0
}

//export Language_Region_String
func Language_Region_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Region](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Region_TLD
func Language_Region_TLD(self C.uint64_t) C.Language_Region_TLD_Result {
	obj := mustLoadHandle[*language.Region](self)
	out0, out1 := obj.TLD()
	v0 := registerStructValue(out0)
	v1 := registerObject(out1)
	return C.Language_Region_TLD_Result{
		v0: v0,
		v1: v1,
	}
}
