// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
	"unsafe"
)

//export Language_Extension_Ctor
func Language_Extension_Ctor() C.uint64_t {
	value := &language.Extension{}
	return registerObject(value)
}

//export Language_Extension_String
func Language_Extension_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Extension](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}

//export Language_Extension_Tokens
func Language_Extension_Tokens(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*language.Extension](self)
	out0 := obj.Tokens()
	var ret0ElemZero *C.char
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((**C.char)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.CString(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Language_Extension_Type
func Language_Extension_Type(self C.uint64_t) C.uint8_t {
	obj := mustLoadHandle[*language.Extension](self)
	out0 := obj.Type()
	ret0 := C.uint8_t(uint8(out0))
	return ret0
}
