// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	language "golang.org/x/text/language"
)

//export Language_Script_Ctor
func Language_Script_Ctor() C.uint64_t {
	value := &language.Script{}
	return registerObject(value)
}

//export Language_Script_IsPrivateUse
func Language_Script_IsPrivateUse(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*language.Script](self)
	out0 := obj.IsPrivateUse()
	ret0 := toCBool(out0)
	return ret0
}

//export Language_Script_String
func Language_Script_String(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*language.Script](self)
	out0 := obj.String()
	ret0 := C.CString(out0)
	return ret0
}
