// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	player "github.com/df-mc/dragonfly/server/player"
	world "github.com/df-mc/dragonfly/server/world"
)

//export Player_Config_Ctor
func Player_Config_Ctor() C.uint64_t {
	value := &player.Config{}
	return registerObject(value)
}

//export Player_Config_Apply
func Player_Config_Apply(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Config](self)
	obj.Apply(mustLoadHandle[*world.EntityData](p1))
}
