// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	block "github.com/df-mc/dragonfly/server/block"
	cube "github.com/df-mc/dragonfly/server/block/cube"
	cmd "github.com/df-mc/dragonfly/server/cmd"
	effect "github.com/df-mc/dragonfly/server/entity/effect"
	item "github.com/df-mc/dragonfly/server/item"
	player "github.com/df-mc/dragonfly/server/player"
	bossbar "github.com/df-mc/dragonfly/server/player/bossbar"
	chat "github.com/df-mc/dragonfly/server/player/chat"
	debug "github.com/df-mc/dragonfly/server/player/debug"
	dialogue "github.com/df-mc/dragonfly/server/player/dialogue"
	form "github.com/df-mc/dragonfly/server/player/form"
	hud "github.com/df-mc/dragonfly/server/player/hud"
	scoreboard "github.com/df-mc/dragonfly/server/player/scoreboard"
	skin "github.com/df-mc/dragonfly/server/player/skin"
	title "github.com/df-mc/dragonfly/server/player/title"
	session "github.com/df-mc/dragonfly/server/session"
	world "github.com/df-mc/dragonfly/server/world"
	mgl64 "github.com/go-gl/mathgl/mgl64"
	time "time"
	"unsafe"
)

//export Player_Player_Ctor
func Player_Player_Ctor() C.uint64_t {
	value := &player.Player{}
	return registerObject(value)
}

//export Player_Player_AbortBreaking
func Player_Player_AbortBreaking(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.AbortBreaking()
}

//export Player_Player_Absorption
func Player_Player_Absorption(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Absorption()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_AddDebugShape
func Player_Player_AddDebugShape(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.AddDebugShape(mustLoadHandle[debug.Shape](p1))
}

//export Player_Player_AddEffect
func Player_Player_AddEffect(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.AddEffect(mustLoadStructValue[effect.Effect](p1))
}

//export Player_Player_AddExperience
func Player_Player_AddExperience(self C.uint64_t, p1 C.int) C.int {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.AddExperience(int(p1))
	ret0 := C.int(int(out0))
	return ret0
}

//export Player_Player_AddFood
func Player_Player_AddFood(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.AddFood(int(p1))
}

//export Player_Player_Addr
func Player_Player_Addr(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Addr()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_AirSupply
func Player_Player_AirSupply(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.AirSupply()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Player_Player_Armour
func Player_Player_Armour(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Armour()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_AttackEntity
func Player_Player_AttackEntity(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.AttackEntity(mustLoadHandle[world.Entity](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_BeaconAffected
func Player_Player_BeaconAffected(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.BeaconAffected()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_BreakBlock
func Player_Player_BreakBlock(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.BreakBlock(mustLoadHandle[cube.Pos](p1))
}

//export Player_Player_Breathing
func Player_Player_Breathing(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Breathing()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Chat
func Player_Player_Chat(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Chat(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_Close
func Player_Player_Close(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Close()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_CloseDialogue
func Player_Player_CloseDialogue(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.CloseDialogue()
}

//export Player_Player_CloseForm
func Player_Player_CloseForm(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.CloseForm()
}

//export Player_Player_Collect
func Player_Player_Collect(self C.uint64_t, p1 C.uint64_t) C.Player_Player_Collect_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1 := obj.Collect(mustLoadStructValue[item.Stack](p1))
	v0 := C.int(int(out0))
	v1 := toCBool(out1)
	return C.Player_Player_Collect_Result{
		v0: v0,
		v1: v1,
	}
}

//export Player_Player_CollectExperience
func Player_Player_CollectExperience(self C.uint64_t, p1 C.int) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.CollectExperience(int(p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_ContinueBreaking
func Player_Player_ContinueBreaking(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ContinueBreaking(cube.Face(int(p1)))
}

//export Player_Player_Crawling
func Player_Player_Crawling(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Crawling()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Data
func Player_Player_Data(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Data()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Player_Player_Dead
func Player_Player_Dead(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Dead()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_DeathPosition
func Player_Player_DeathPosition(self C.uint64_t) C.Player_Player_DeathPosition_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1, out2 := obj.DeathPosition()
	v0Slice := out0[:]
	var v0ElemZero C.double
	v0ElemSize := C.int(unsafe.Sizeof(v0ElemZero))
	v0 := C.GoArray{data: nil, length: 0, elementSize: v0ElemSize}
	if len(v0Slice) > 0 {
		totalSize := C.size_t(len(v0Slice)) * C.size_t(v0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(v0Slice))
			for i := 0; i < len(v0Slice); i++ {
				buf[i] = C.double(float64(v0Slice[i]))
			}
			v0.data = data
			v0.length = C.int(len(v0Slice))
		}
	}
	v1 := registerObject(out1)
	v2 := toCBool(out2)
	return C.Player_Player_DeathPosition_Result{
		v0: v0,
		v1: v1,
		v2: v2,
	}
}

//export Player_Player_DeviceID
func Player_Player_DeviceID(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.DeviceID()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_DeviceModel
func Player_Player_DeviceModel(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.DeviceModel()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_DisableInstantRespawn
func Player_Player_DisableInstantRespawn(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.DisableInstantRespawn()
}

//export Player_Player_Disconnect
func Player_Player_Disconnect(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Disconnect(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_Drop
func Player_Player_Drop(self C.uint64_t, p1 C.uint64_t) C.int {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Drop(mustLoadStructValue[item.Stack](p1))
	ret0 := C.int(int(out0))
	return ret0
}

//export Player_Player_EditSign
func Player_Player_EditSign(self C.uint64_t, p1 C.uint64_t, p2 *C.char, p3 *C.char) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.EditSign(mustLoadHandle[cube.Pos](p1), C.GoString(p2), C.GoString(p3))
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Effect
func Player_Player_Effect(self C.uint64_t, p1 C.uint64_t) C.Player_Player_Effect_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1 := obj.Effect(mustLoadHandle[effect.Type](p1))
	v0 := registerStructValue(out0)
	v1 := toCBool(out1)
	return C.Player_Player_Effect_Result{
		v0: v0,
		v1: v1,
	}
}

//export Player_Player_Effects
func Player_Player_Effects(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Effects()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerStructValue(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Player_Player_EnableInstantRespawn
func Player_Player_EnableInstantRespawn(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.EnableInstantRespawn()
}

//export Player_Player_EnchantmentSeed
func Player_Player_EnchantmentSeed(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.EnchantmentSeed()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Player_Player_EnderChestInventory
func Player_Player_EnderChestInventory(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.EnderChestInventory()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_ExecuteCommand
func Player_Player_ExecuteCommand(self C.uint64_t, p1 *C.char) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ExecuteCommand(C.GoString(p1))
}

//export Player_Player_Exhaust
func Player_Player_Exhaust(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Exhaust(float64(p1))
}

//export Player_Player_Experience
func Player_Player_Experience(self C.uint64_t) C.int {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Experience()
	ret0 := C.int(int(out0))
	return ret0
}

//export Player_Player_ExperienceLevel
func Player_Player_ExperienceLevel(self C.uint64_t) C.int {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.ExperienceLevel()
	ret0 := C.int(int(out0))
	return ret0
}

//export Player_Player_ExperienceProgress
func Player_Player_ExperienceProgress(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.ExperienceProgress()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_Explode
func Player_Player_Explode(self C.uint64_t, p1 C.uint64_t, p2 C.double, p3 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Explode(mustLoadHandle[mgl64.Vec3](p1), float64(p2), mustLoadStructValue[block.ExplosionConfig](p3))
}

//export Player_Player_Extinguish
func Player_Player_Extinguish(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Extinguish()
}

//export Player_Player_EyeHeight
func Player_Player_EyeHeight(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.EyeHeight()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_FallDistance
func Player_Player_FallDistance(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.FallDistance()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_FinalDamageFrom
func Player_Player_FinalDamageFrom(self C.uint64_t, p1 C.double, p2 C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.FinalDamageFrom(float64(p1), mustLoadHandle[world.DamageSource](p2))
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_FinishBreaking
func Player_Player_FinishBreaking(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.FinishBreaking()
}

//export Player_Player_FireProof
func Player_Player_FireProof(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.FireProof()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_FlightSpeed
func Player_Player_FlightSpeed(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.FlightSpeed()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_Flying
func Player_Player_Flying(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Flying()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Food
func Player_Player_Food(self C.uint64_t) C.int {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Food()
	ret0 := C.int(int(out0))
	return ret0
}

//export Player_Player_GameMode
func Player_Player_GameMode(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.GameMode()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Gliding
func Player_Player_Gliding(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Gliding()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_H
func Player_Player_H(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.H()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Handle
func Player_Player_Handle(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Handle(mustLoadHandle[player.Handler](p1))
}

//export Player_Player_Handler
func Player_Player_Handler(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Handler()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_HasCooldown
func Player_Player_HasCooldown(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.HasCooldown(mustLoadHandle[world.Item](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Heal
func Player_Player_Heal(self C.uint64_t, p1 C.double, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Heal(float64(p1), mustLoadHandle[world.HealingSource](p2))
}

//export Player_Player_Health
func Player_Player_Health(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Health()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_HeldItems
func Player_Player_HeldItems(self C.uint64_t) C.Player_Player_HeldItems_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1 := obj.HeldItems()
	v0 := registerStructValue(out0)
	v1 := registerStructValue(out1)
	return C.Player_Player_HeldItems_Result{
		v0: v0,
		v1: v1,
	}
}

//export Player_Player_HideCoordinates
func Player_Player_HideCoordinates(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.HideCoordinates()
}

//export Player_Player_HideEntity
func Player_Player_HideEntity(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.HideEntity(mustLoadHandle[world.Entity](p1))
}

//export Player_Player_HideHudElement
func Player_Player_HideHudElement(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.HideHudElement(mustLoadStructValue[hud.Element](p1))
}

//export Player_Player_HudElementHidden
func Player_Player_HudElementHidden(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.HudElementHidden(mustLoadStructValue[hud.Element](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Hurt
func Player_Player_Hurt(self C.uint64_t, p1 C.double, p2 C.uint64_t) C.Player_Player_Hurt_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1 := obj.Hurt(float64(p1), mustLoadHandle[world.DamageSource](p2))
	v0 := C.double(float64(out0))
	v1 := toCBool(out1)
	return C.Player_Player_Hurt_Result{
		v0: v0,
		v1: v1,
	}
}

//export Player_Player_Immobile
func Player_Player_Immobile(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Immobile()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Inventory
func Player_Player_Inventory(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Inventory()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Invisible
func Player_Player_Invisible(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Invisible()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Jump
func Player_Player_Jump(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Jump()
}

//export Player_Player_KnockBack
func Player_Player_KnockBack(self C.uint64_t, p1 C.uint64_t, p2 C.double, p3 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.KnockBack(mustLoadHandle[mgl64.Vec3](p1), float64(p2), float64(p3))
}

//export Player_Player_Latency
func Player_Player_Latency(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Latency()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Player_Player_Locale
func Player_Player_Locale(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Locale()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Player_Player_MaxAirSupply
func Player_Player_MaxAirSupply(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.MaxAirSupply()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Player_Player_MaxHealth
func Player_Player_MaxHealth(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.MaxHealth()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_Message
func Player_Player_Message(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Message(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_Messagef
func Player_Player_Messagef(self C.uint64_t, p1 *C.char, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Messagef(C.GoString(p1), mustLoadHandle[[]interface{}](p2)...)
}

//export Player_Player_Messaget
func Player_Player_Messaget(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Messaget(mustLoadStructValue[chat.Translation](p1), mustLoadHandle[[]interface{}](p2)...)
}

//export Player_Player_Move
func Player_Player_Move(self C.uint64_t, p1 C.uint64_t, p2 C.double, p3 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Move(mustLoadHandle[mgl64.Vec3](p1), float64(p2), float64(p3))
}

//export Player_Player_MoveItemsToInventory
func Player_Player_MoveItemsToInventory(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.MoveItemsToInventory()
}

//export Player_Player_Name
func Player_Player_Name(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Name()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_NameTag
func Player_Player_NameTag(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.NameTag()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_OnFireDuration
func Player_Player_OnFireDuration(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.OnFireDuration()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Player_Player_OnGround
func Player_Player_OnGround(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.OnGround()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_OpenBlockContainer
func Player_Player_OpenBlockContainer(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.OpenBlockContainer(mustLoadHandle[cube.Pos](p1), mustLoadHandle[*world.Tx](p2))
}

//export Player_Player_OpenSign
func Player_Player_OpenSign(self C.uint64_t, p1 C.uint64_t, p2 C.bool) {
	obj := mustLoadHandle[*player.Player](self)
	obj.OpenSign(mustLoadHandle[cube.Pos](p1), fromCBool(p2))
}

//export Player_Player_PickBlock
func Player_Player_PickBlock(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.PickBlock(mustLoadHandle[cube.Pos](p1))
}

//export Player_Player_PlaceBlock
func Player_Player_PlaceBlock(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t, p3 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.PlaceBlock(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Block](p2), mustLoadHandle[*item.UseContext](p3))
}

//export Player_Player_PlaySound
func Player_Player_PlaySound(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.PlaySound(mustLoadHandle[world.Sound](p1))
}

//export Player_Player_Position
func Player_Player_Position(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Position()
	ret0Slice := out0[:]
	var ret0ElemZero C.double
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.double(float64(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Player_Player_PunchAir
func Player_Player_PunchAir(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.PunchAir()
}

//export Player_Player_ReleaseItem
func Player_Player_ReleaseItem(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ReleaseItem()
}

//export Player_Player_RemoveAllDebugShapes
func Player_Player_RemoveAllDebugShapes(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveAllDebugShapes()
}

//export Player_Player_RemoveBossBar
func Player_Player_RemoveBossBar(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveBossBar()
}

//export Player_Player_RemoveDebugShape
func Player_Player_RemoveDebugShape(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveDebugShape(mustLoadHandle[debug.Shape](p1))
}

//export Player_Player_RemoveEffect
func Player_Player_RemoveEffect(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveEffect(mustLoadHandle[effect.Type](p1))
}

//export Player_Player_RemoveExperience
func Player_Player_RemoveExperience(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveExperience(int(p1))
}

//export Player_Player_RemoveScoreboard
func Player_Player_RemoveScoreboard(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.RemoveScoreboard()
}

//export Player_Player_ResetEnchantmentSeed
func Player_Player_ResetEnchantmentSeed(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ResetEnchantmentSeed()
}

//export Player_Player_ResetFallDistance
func Player_Player_ResetFallDistance(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ResetFallDistance()
}

//export Player_Player_Respawn
func Player_Player_Respawn(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Respawn()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Rotation
func Player_Player_Rotation(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Rotation()
	ret0Slice := out0[:]
	var ret0ElemZero C.double
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.double(float64(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Player_Player_Saturate
func Player_Player_Saturate(self C.uint64_t, p1 C.int, p2 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Saturate(int(p1), float64(p2))
}

//export Player_Player_Scale
func Player_Player_Scale(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Scale()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_ScoreTag
func Player_Player_ScoreTag(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.ScoreTag()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_SelfSignedID
func Player_Player_SelfSignedID(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.SelfSignedID()
	ret0 := C.CString(out0)
	return ret0
}

//export Player_Player_SendBossBar
func Player_Player_SendBossBar(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendBossBar(mustLoadStructValue[bossbar.BossBar](p1))
}

//export Player_Player_SendCommandOutput
func Player_Player_SendCommandOutput(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendCommandOutput(mustLoadHandle[*cmd.Output](p1))
}

//export Player_Player_SendDialogue
func Player_Player_SendDialogue(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendDialogue(mustLoadStructValue[dialogue.Dialogue](p1), mustLoadHandle[world.Entity](p2))
}

//export Player_Player_SendForm
func Player_Player_SendForm(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendForm(mustLoadHandle[form.Form](p1))
}

//export Player_Player_SendJukeboxPopup
func Player_Player_SendJukeboxPopup(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendJukeboxPopup(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_SendPopup
func Player_Player_SendPopup(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendPopup(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_SendScoreboard
func Player_Player_SendScoreboard(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendScoreboard(mustLoadHandle[*scoreboard.Scoreboard](p1))
}

//export Player_Player_SendSleepingIndicator
func Player_Player_SendSleepingIndicator(self C.uint64_t, p1 C.int, p2 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendSleepingIndicator(int(p1), int(p2))
}

//export Player_Player_SendTip
func Player_Player_SendTip(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendTip(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_SendTitle
func Player_Player_SendTitle(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendTitle(mustLoadStructValue[title.Title](p1))
}

//export Player_Player_SendToast
func Player_Player_SendToast(self C.uint64_t, p1 *C.char, p2 *C.char) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SendToast(C.GoString(p1), C.GoString(p2))
}

//export Player_Player_SetAbsorption
func Player_Player_SetAbsorption(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetAbsorption(float64(p1))
}

//export Player_Player_SetAirSupply
func Player_Player_SetAirSupply(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetAirSupply(time.Duration(int64(p1)))
}

//export Player_Player_SetCooldown
func Player_Player_SetCooldown(self C.uint64_t, p1 C.uint64_t, p2 C.int64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetCooldown(mustLoadHandle[world.Item](p1), time.Duration(int64(p2)))
}

//export Player_Player_SetExperienceLevel
func Player_Player_SetExperienceLevel(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetExperienceLevel(int(p1))
}

//export Player_Player_SetExperienceProgress
func Player_Player_SetExperienceProgress(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetExperienceProgress(float64(p1))
}

//export Player_Player_SetFlightSpeed
func Player_Player_SetFlightSpeed(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetFlightSpeed(float64(p1))
}

//export Player_Player_SetFood
func Player_Player_SetFood(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetFood(int(p1))
}

//export Player_Player_SetGameMode
func Player_Player_SetGameMode(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetGameMode(mustLoadHandle[world.GameMode](p1))
}

//export Player_Player_SetHeldItems
func Player_Player_SetHeldItems(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetHeldItems(mustLoadStructValue[item.Stack](p1), mustLoadStructValue[item.Stack](p2))
}

//export Player_Player_SetHeldSlot
func Player_Player_SetHeldSlot(self C.uint64_t, p1 C.int) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.SetHeldSlot(int(p1))
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_SetImmobile
func Player_Player_SetImmobile(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetImmobile()
}

//export Player_Player_SetInvisible
func Player_Player_SetInvisible(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetInvisible()
}

//export Player_Player_SetMaxAirSupply
func Player_Player_SetMaxAirSupply(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetMaxAirSupply(time.Duration(int64(p1)))
}

//export Player_Player_SetMaxHealth
func Player_Player_SetMaxHealth(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetMaxHealth(float64(p1))
}

//export Player_Player_SetMobile
func Player_Player_SetMobile(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetMobile()
}

//export Player_Player_SetNameTag
func Player_Player_SetNameTag(self C.uint64_t, p1 *C.char) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetNameTag(C.GoString(p1))
}

//export Player_Player_SetOnFire
func Player_Player_SetOnFire(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetOnFire(time.Duration(int64(p1)))
}

//export Player_Player_SetScale
func Player_Player_SetScale(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetScale(float64(p1))
}

//export Player_Player_SetScoreTag
func Player_Player_SetScoreTag(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetScoreTag(mustLoadHandle[[]interface{}](p1)...)
}

//export Player_Player_SetSkin
func Player_Player_SetSkin(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetSkin(mustLoadStructValue[skin.Skin](p1))
}

//export Player_Player_SetSpeed
func Player_Player_SetSpeed(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetSpeed(float64(p1))
}

//export Player_Player_SetVelocity
func Player_Player_SetVelocity(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetVelocity(mustLoadHandle[mgl64.Vec3](p1))
}

//export Player_Player_SetVerticalFlightSpeed
func Player_Player_SetVerticalFlightSpeed(self C.uint64_t, p1 C.double) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetVerticalFlightSpeed(float64(p1))
}

//export Player_Player_SetVisible
func Player_Player_SetVisible(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SetVisible()
}

//export Player_Player_ShowCoordinates
func Player_Player_ShowCoordinates(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ShowCoordinates()
}

//export Player_Player_ShowEntity
func Player_Player_ShowEntity(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ShowEntity(mustLoadHandle[world.Entity](p1))
}

//export Player_Player_ShowHudElement
func Player_Player_ShowHudElement(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ShowHudElement(mustLoadStructValue[hud.Element](p1))
}

//export Player_Player_ShowParticle
func Player_Player_ShowParticle(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.ShowParticle(mustLoadHandle[mgl64.Vec3](p1), mustLoadHandle[world.Particle](p2))
}

//export Player_Player_Skin
func Player_Player_Skin(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Skin()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Player_Player_Sleep
func Player_Player_Sleep(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Sleep(mustLoadHandle[cube.Pos](p1))
}

//export Player_Player_Sleeping
func Player_Player_Sleeping(self C.uint64_t) C.Player_Player_Sleeping_Result {
	obj := mustLoadHandle[*player.Player](self)
	out0, out1 := obj.Sleeping()
	v0Slice := out0[:]
	var v0ElemZero C.int
	v0ElemSize := C.int(unsafe.Sizeof(v0ElemZero))
	v0 := C.GoArray{data: nil, length: 0, elementSize: v0ElemSize}
	if len(v0Slice) > 0 {
		totalSize := C.size_t(len(v0Slice)) * C.size_t(v0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.int)(data), len(v0Slice))
			for i := 0; i < len(v0Slice); i++ {
				buf[i] = C.int(int(v0Slice[i]))
			}
			v0.data = data
			v0.length = C.int(len(v0Slice))
		}
	}
	v1 := toCBool(out1)
	return C.Player_Player_Sleeping_Result{
		v0: v0,
		v1: v1,
	}
}

//export Player_Player_Sneaking
func Player_Player_Sneaking(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Sneaking()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Speed
func Player_Player_Speed(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Speed()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_Splash
func Player_Player_Splash(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Splash(mustLoadHandle[*world.Tx](p1), mustLoadHandle[mgl64.Vec3](p2))
}

//export Player_Player_Sprinting
func Player_Player_Sprinting(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Sprinting()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_StartBreaking
func Player_Player_StartBreaking(self C.uint64_t, p1 C.uint64_t, p2 C.int) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartBreaking(mustLoadHandle[cube.Pos](p1), cube.Face(int(p2)))
}

//export Player_Player_StartCrawling
func Player_Player_StartCrawling(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartCrawling()
}

//export Player_Player_StartFlying
func Player_Player_StartFlying(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartFlying()
}

//export Player_Player_StartGliding
func Player_Player_StartGliding(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartGliding()
}

//export Player_Player_StartSneaking
func Player_Player_StartSneaking(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartSneaking()
}

//export Player_Player_StartSprinting
func Player_Player_StartSprinting(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartSprinting()
}

//export Player_Player_StartSwimming
func Player_Player_StartSwimming(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StartSwimming()
}

//export Player_Player_StopCrawling
func Player_Player_StopCrawling(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopCrawling()
}

//export Player_Player_StopFlying
func Player_Player_StopFlying(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopFlying()
}

//export Player_Player_StopGliding
func Player_Player_StopGliding(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopGliding()
}

//export Player_Player_StopSneaking
func Player_Player_StopSneaking(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopSneaking()
}

//export Player_Player_StopSprinting
func Player_Player_StopSprinting(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopSprinting()
}

//export Player_Player_StopSwimming
func Player_Player_StopSwimming(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.StopSwimming()
}

//export Player_Player_Swimming
func Player_Player_Swimming(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Swimming()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_SwingArm
func Player_Player_SwingArm(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.SwingArm()
}

//export Player_Player_Teleport
func Player_Player_Teleport(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Teleport(mustLoadHandle[mgl64.Vec3](p1))
}

//export Player_Player_Tick
func Player_Player_Tick(self C.uint64_t, p1 C.uint64_t, p2 C.int64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Tick(mustLoadHandle[*world.Tx](p1), int64(p2))
}

//export Player_Player_TorsoHeight
func Player_Player_TorsoHeight(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.TorsoHeight()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_Transfer
func Player_Player_Transfer(self C.uint64_t, p1 *C.char) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Transfer(C.GoString(p1))
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_TurnLecternPage
func Player_Player_TurnLecternPage(self C.uint64_t, p1 C.uint64_t, p2 C.int) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.TurnLecternPage(mustLoadHandle[cube.Pos](p1), int(p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_Tx
func Player_Player_Tx(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Tx()
	ret0 := registerObject(out0)
	return ret0
}

//export Player_Player_UUID
func Player_Player_UUID(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.UUID()
	ret0Slice := out0[:]
	var ret0ElemZero C.uint8_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint8_t)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.uint8_t(uint8(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Player_Player_UpdateDiagnostics
func Player_Player_UpdateDiagnostics(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.UpdateDiagnostics(mustLoadStructValue[session.Diagnostics](p1))
}

//export Player_Player_UseItem
func Player_Player_UseItem(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.UseItem()
}

//export Player_Player_UseItemOnBlock
func Player_Player_UseItemOnBlock(self C.uint64_t, p1 C.uint64_t, p2 C.int, p3 C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.UseItemOnBlock(mustLoadHandle[cube.Pos](p1), cube.Face(int(p2)), mustLoadHandle[mgl64.Vec3](p3))
}

//export Player_Player_UseItemOnEntity
func Player_Player_UseItemOnEntity(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.UseItemOnEntity(mustLoadHandle[world.Entity](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_UsingItem
func Player_Player_UsingItem(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.UsingItem()
	ret0 := toCBool(out0)
	return ret0
}

//export Player_Player_Velocity
func Player_Player_Velocity(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.Velocity()
	ret0Slice := out0[:]
	var ret0ElemZero C.double
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.double)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.double(float64(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export Player_Player_VerticalFlightSpeed
func Player_Player_VerticalFlightSpeed(self C.uint64_t) C.double {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.VerticalFlightSpeed()
	ret0 := C.double(float64(out0))
	return ret0
}

//export Player_Player_VisibleDebugShapes
func Player_Player_VisibleDebugShapes(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.VisibleDebugShapes()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Player_Player_Wake
func Player_Player_Wake(self C.uint64_t) {
	obj := mustLoadHandle[*player.Player](self)
	obj.Wake()
}

//export Player_Player_XUID
func Player_Player_XUID(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*player.Player](self)
	out0 := obj.XUID()
	ret0 := C.CString(out0)
	return ret0
}
