// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	"fmt"
	"sync"
	"sync/atomic"
	"unsafe"
)

var (
	handleCounter atomic.Uint64
	handleStore   sync.Map
)

func registerObject(value any) C.uint64_t {
	if value == nil {
		return 0
	}
	handle := handleCounter.Add(1)
	handleStore.Store(handle, value)
	return C.uint64_t(handle)
}

func registerStructValue[T any](value T) C.uint64_t {
	copyValue := value
	return registerObject(&copyValue)
}

func mustLoadHandle[T any](handle C.uint64_t) T {
	var zero T
	if handle == 0 {
		return zero
	}
	raw, ok := handleStore.Load(uint64(handle))
	if !ok {
		panic(fmt.Sprintf("generator: unknown handle %d", uint64(handle)))
	}
	resolved, ok := raw.(T)
	if !ok {
		panic(fmt.Sprintf("generator: handle %d has incompatible type", uint64(handle)))
	}
	return resolved
}

func mustLoadStructValue[T any](handle C.uint64_t) T {
	var zero T
	if handle == 0 {
		return zero
	}
	ptr := mustLoadHandle[*T](handle)
	if ptr == nil {
		return zero
	}
	return *ptr
}

func toCBool(value bool) C.bool {
	return C.bool(value)
}

func fromCBool(value C.bool) bool {
	return bool(value)
}

//export Go_ReleaseHandle
func Go_ReleaseHandle(handle C.uint64_t) {
	if handle == 0 {
		return
	}
	handleStore.Delete(uint64(handle))
}

//export C_FreeString
func C_FreeString(value *C.char) {
	if value == nil {
		return
	}
	C.free(unsafe.Pointer(value))
}

//export C_FreeMemory
func C_FreeMemory(value unsafe.Pointer) {
	if value == nil {
		return
	}
	C.free(value)
}
