// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	scoreboard "github.com/df-mc/dragonfly/server/player/scoreboard"
	"unsafe"
)

//export Scoreboard_Scoreboard_Ctor
func Scoreboard_Scoreboard_Ctor() C.uint64_t {
	value := &scoreboard.Scoreboard{}
	return registerObject(value)
}

//export Scoreboard_Scoreboard_Descending
func Scoreboard_Scoreboard_Descending(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	out0 := obj.Descending()
	ret0 := toCBool(out0)
	return ret0
}

//export Scoreboard_Scoreboard_Lines
func Scoreboard_Scoreboard_Lines(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	out0 := obj.Lines()
	var ret0ElemZero *C.char
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((**C.char)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = C.CString(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export Scoreboard_Scoreboard_Name
func Scoreboard_Scoreboard_Name(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	out0 := obj.Name()
	ret0 := C.CString(out0)
	return ret0
}

//export Scoreboard_Scoreboard_Remove
func Scoreboard_Scoreboard_Remove(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	obj.Remove(int(p1))
}

//export Scoreboard_Scoreboard_RemovePadding
func Scoreboard_Scoreboard_RemovePadding(self C.uint64_t) {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	obj.RemovePadding()
}

//export Scoreboard_Scoreboard_Set
func Scoreboard_Scoreboard_Set(self C.uint64_t, p1 C.int, p2 *C.char) {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	obj.Set(int(p1), C.GoString(p2))
}

//export Scoreboard_Scoreboard_SetDescending
func Scoreboard_Scoreboard_SetDescending(self C.uint64_t) {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	obj.SetDescending()
}

//export Scoreboard_Scoreboard_Write
func Scoreboard_Scoreboard_Write(self C.uint64_t, p1 C.uint64_t) C.Scoreboard_Scoreboard_Write_Result {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	out0, out1 := obj.Write(mustLoadHandle[[]uint8](p1))
	v0 := C.int(int(out0))
	v1 := registerObject(out1)
	return C.Scoreboard_Scoreboard_Write_Result{
		v0: v0,
		v1: v1,
	}
}

//export Scoreboard_Scoreboard_WriteString
func Scoreboard_Scoreboard_WriteString(self C.uint64_t, p1 *C.char) C.Scoreboard_Scoreboard_WriteString_Result {
	obj := mustLoadHandle[*scoreboard.Scoreboard](self)
	out0, out1 := obj.WriteString(C.GoString(p1))
	v0 := C.int(int(out0))
	v1 := registerObject(out1)
	return C.Scoreboard_Scoreboard_WriteString_Result{
		v0: v0,
		v1: v1,
	}
}
