// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	session "github.com/df-mc/dragonfly/server/session"
)

//export Session_Diagnostics_Ctor
func Session_Diagnostics_Ctor() C.uint64_t {
	value := &session.Diagnostics{}
	return registerObject(value)
}
