// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	skin "github.com/df-mc/dragonfly/server/player/skin"
)

//export Skin_Skin_Ctor
func Skin_Skin_Ctor() C.uint64_t {
	value := &skin.Skin{}
	return registerObject(value)
}

//export Skin_Skin_At
func Skin_Skin_At(self C.uint64_t, p1 C.int, p2 C.int) C.uint64_t {
	obj := mustLoadHandle[*skin.Skin](self)
	out0 := obj.At(int(p1), int(p2))
	ret0 := registerObject(out0)
	return ret0
}

//export Skin_Skin_Bounds
func Skin_Skin_Bounds(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*skin.Skin](self)
	out0 := obj.Bounds()
	ret0 := registerStructValue(out0)
	return ret0
}

//export Skin_Skin_ColorModel
func Skin_Skin_ColorModel(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*skin.Skin](self)
	out0 := obj.ColorModel()
	ret0 := registerObject(out0)
	return ret0
}
