// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	title "github.com/df-mc/dragonfly/server/player/title"
	time "time"
)

//export Title_Title_Ctor
func Title_Title_Ctor() C.uint64_t {
	value := &title.Title{}
	return registerObject(value)
}

//export Title_Title_ActionText
func Title_Title_ActionText(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.ActionText()
	ret0 := C.CString(out0)
	return ret0
}

//export Title_Title_Duration
func Title_Title_Duration(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.Duration()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Title_Title_FadeInDuration
func Title_Title_FadeInDuration(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.FadeInDuration()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Title_Title_FadeOutDuration
func Title_Title_FadeOutDuration(self C.uint64_t) C.int64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.FadeOutDuration()
	ret0 := C.int64_t(int64(out0))
	return ret0
}

//export Title_Title_Subtitle
func Title_Title_Subtitle(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.Subtitle()
	ret0 := C.CString(out0)
	return ret0
}

//export Title_Title_Text
func Title_Title_Text(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.Text()
	ret0 := C.CString(out0)
	return ret0
}

//export Title_Title_WithActionText
func Title_Title_WithActionText(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.WithActionText(mustLoadHandle[[]interface{}](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}

//export Title_Title_WithDuration
func Title_Title_WithDuration(self C.uint64_t, p1 C.int64_t) C.uint64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.WithDuration(time.Duration(int64(p1)))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Title_Title_WithFadeInDuration
func Title_Title_WithFadeInDuration(self C.uint64_t, p1 C.int64_t) C.uint64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.WithFadeInDuration(time.Duration(int64(p1)))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Title_Title_WithFadeOutDuration
func Title_Title_WithFadeOutDuration(self C.uint64_t, p1 C.int64_t) C.uint64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.WithFadeOutDuration(time.Duration(int64(p1)))
	ret0 := registerStructValue(out0)
	return ret0
}

//export Title_Title_WithSubtitle
func Title_Title_WithSubtitle(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*title.Title](self)
	out0 := obj.WithSubtitle(mustLoadHandle[[]interface{}](p1)...)
	ret0 := registerStructValue(out0)
	return ret0
}
