// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	world "github.com/df-mc/dragonfly/server/world"
)

//export World_EntityRegistryConfig_Ctor
func World_EntityRegistryConfig_Ctor() C.uint64_t {
	value := &world.EntityRegistryConfig{}
	return registerObject(value)
}

//export World_EntityRegistryConfig_New
func World_EntityRegistryConfig_New(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.EntityRegistryConfig](self)
	out0 := obj.New(mustLoadHandle[[]world.EntityType](p1))
	ret0 := registerStructValue(out0)
	return ret0
}
