// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	world "github.com/df-mc/dragonfly/server/world"
)

//export World_EntityAnimation_Ctor
func World_EntityAnimation_Ctor() C.uint64_t {
	value := &world.EntityAnimation{}
	return registerObject(value)
}

//export World_EntityAnimation_Controller
func World_EntityAnimation_Controller(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.Controller()
	ret0 := C.CString(out0)
	return ret0
}

//export World_EntityAnimation_Name
func World_EntityAnimation_Name(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.Name()
	ret0 := C.CString(out0)
	return ret0
}

//export World_EntityAnimation_NextState
func World_EntityAnimation_NextState(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.NextState()
	ret0 := C.CString(out0)
	return ret0
}

//export World_EntityAnimation_StopCondition
func World_EntityAnimation_StopCondition(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.StopCondition()
	ret0 := C.CString(out0)
	return ret0
}

//export World_EntityAnimation_WithController
func World_EntityAnimation_WithController(self C.uint64_t, p1 *C.char) C.uint64_t {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.WithController(C.GoString(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export World_EntityAnimation_WithNextState
func World_EntityAnimation_WithNextState(self C.uint64_t, p1 *C.char) C.uint64_t {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.WithNextState(C.GoString(p1))
	ret0 := registerStructValue(out0)
	return ret0
}

//export World_EntityAnimation_WithStopCondition
func World_EntityAnimation_WithStopCondition(self C.uint64_t, p1 *C.char) C.uint64_t {
	obj := mustLoadHandle[*world.EntityAnimation](self)
	out0 := obj.WithStopCondition(C.GoString(p1))
	ret0 := registerStructValue(out0)
	return ret0
}
