// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	world "github.com/df-mc/dragonfly/server/world"
	"unsafe"
)

//export World_EntityRegistry_Ctor
func World_EntityRegistry_Ctor() C.uint64_t {
	value := &world.EntityRegistry{}
	return registerObject(value)
}

//export World_EntityRegistry_Config
func World_EntityRegistry_Config(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.EntityRegistry](self)
	out0 := obj.Config()
	ret0 := registerStructValue(out0)
	return ret0
}

//export World_EntityRegistry_Lookup
func World_EntityRegistry_Lookup(self C.uint64_t, p1 *C.char) C.World_EntityRegistry_Lookup_Result {
	obj := mustLoadHandle[*world.EntityRegistry](self)
	out0, out1 := obj.Lookup(C.GoString(p1))
	v0 := registerObject(out0)
	v1 := toCBool(out1)
	return C.World_EntityRegistry_Lookup_Result{
		v0: v0,
		v1: v1,
	}
}

//export World_EntityRegistry_Types
func World_EntityRegistry_Types(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.EntityRegistry](self)
	out0 := obj.Types()
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}
