// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	cube "github.com/df-mc/dragonfly/server/block/cube"
	world "github.com/df-mc/dragonfly/server/world"
	mgl64 "github.com/go-gl/mathgl/mgl64"
	time "time"
	"unsafe"
)

//export World_Tx_Ctor
func World_Tx_Ctor() C.uint64_t {
	value := &world.Tx{}
	return registerObject(value)
}

//export World_Tx_AddEntity
func World_Tx_AddEntity(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.AddEntity(mustLoadHandle[*world.EntityHandle](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_AddParticle
func World_Tx_AddParticle(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.AddParticle(mustLoadHandle[mgl64.Vec3](p1), mustLoadHandle[world.Particle](p2))
}

//export World_Tx_Biome
func World_Tx_Biome(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Biome(mustLoadHandle[cube.Pos](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_Block
func World_Tx_Block(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Block(mustLoadHandle[cube.Pos](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_BroadcastSleepingIndicator
func World_Tx_BroadcastSleepingIndicator(self C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.BroadcastSleepingIndicator()
}

//export World_Tx_BroadcastSleepingReminder
func World_Tx_BroadcastSleepingReminder(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.BroadcastSleepingReminder(mustLoadHandle[world.Sleeper](p1))
}

//export World_Tx_BuildStructure
func World_Tx_BuildStructure(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.BuildStructure(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Structure](p2))
}

//export World_Tx_Entities
func World_Tx_Entities(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Entities()
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_EntitiesWithin
func World_Tx_EntitiesWithin(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.EntitiesWithin(mustLoadStructValue[cube.BBox](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_HighestBlock
func World_Tx_HighestBlock(self C.uint64_t, p1 C.int, p2 C.int) C.int {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.HighestBlock(int(p1), int(p2))
	ret0 := C.int(int(out0))
	return ret0
}

//export World_Tx_HighestLightBlocker
func World_Tx_HighestLightBlocker(self C.uint64_t, p1 C.int, p2 C.int) C.int {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.HighestLightBlocker(int(p1), int(p2))
	ret0 := C.int(int(out0))
	return ret0
}

//export World_Tx_Light
func World_Tx_Light(self C.uint64_t, p1 C.uint64_t) C.uint8_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Light(mustLoadHandle[cube.Pos](p1))
	ret0 := C.uint8_t(uint8(out0))
	return ret0
}

//export World_Tx_Liquid
func World_Tx_Liquid(self C.uint64_t, p1 C.uint64_t) C.World_Tx_Liquid_Result {
	obj := mustLoadHandle[*world.Tx](self)
	out0, out1 := obj.Liquid(mustLoadHandle[cube.Pos](p1))
	v0 := registerObject(out0)
	v1 := toCBool(out1)
	return C.World_Tx_Liquid_Result{
		v0: v0,
		v1: v1,
	}
}

//export World_Tx_PlayEntityAnimation
func World_Tx_PlayEntityAnimation(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.PlayEntityAnimation(mustLoadHandle[world.Entity](p1), mustLoadStructValue[world.EntityAnimation](p2))
}

//export World_Tx_PlaySound
func World_Tx_PlaySound(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.PlaySound(mustLoadHandle[mgl64.Vec3](p1), mustLoadHandle[world.Sound](p2))
}

//export World_Tx_Players
func World_Tx_Players(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Players()
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_Raining
func World_Tx_Raining(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Raining()
	ret0 := toCBool(out0)
	return ret0
}

//export World_Tx_RainingAt
func World_Tx_RainingAt(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.RainingAt(mustLoadHandle[cube.Pos](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export World_Tx_Range
func World_Tx_Range(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Range()
	ret0Slice := out0[:]
	var ret0ElemZero C.int
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.int)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.int(int(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export World_Tx_RemoveEntity
func World_Tx_RemoveEntity(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.RemoveEntity(mustLoadHandle[world.Entity](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_ScheduleBlockUpdate
func World_Tx_ScheduleBlockUpdate(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t, p3 C.int64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.ScheduleBlockUpdate(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Block](p2), time.Duration(int64(p3)))
}

//export World_Tx_SetBiome
func World_Tx_SetBiome(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.SetBiome(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Biome](p2))
}

//export World_Tx_SetBlock
func World_Tx_SetBlock(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t, p3 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.SetBlock(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Block](p2), mustLoadHandle[*world.SetOpts](p3))
}

//export World_Tx_SetLiquid
func World_Tx_SetLiquid(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.Tx](self)
	obj.SetLiquid(mustLoadHandle[cube.Pos](p1), mustLoadHandle[world.Liquid](p2))
}

//export World_Tx_SkyLight
func World_Tx_SkyLight(self C.uint64_t, p1 C.uint64_t) C.uint8_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.SkyLight(mustLoadHandle[cube.Pos](p1))
	ret0 := C.uint8_t(uint8(out0))
	return ret0
}

//export World_Tx_Sleepers
func World_Tx_Sleepers(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Sleepers()
	ret0 := registerObject(out0)
	return ret0
}

//export World_Tx_SnowingAt
func World_Tx_SnowingAt(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.SnowingAt(mustLoadHandle[cube.Pos](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export World_Tx_Temperature
func World_Tx_Temperature(self C.uint64_t, p1 C.uint64_t) C.double {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Temperature(mustLoadHandle[cube.Pos](p1))
	ret0 := C.double(float64(out0))
	return ret0
}

//export World_Tx_Thundering
func World_Tx_Thundering(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Thundering()
	ret0 := toCBool(out0)
	return ret0
}

//export World_Tx_ThunderingAt
func World_Tx_ThunderingAt(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.ThunderingAt(mustLoadHandle[cube.Pos](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export World_Tx_Viewers
func World_Tx_Viewers(self C.uint64_t, p1 C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.Viewers(mustLoadHandle[mgl64.Vec3](p1))
	var ret0ElemZero C.uint64_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(out0) > 0 {
		totalSize := C.size_t(len(out0)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint64_t)(data), len(out0))
			for i := 0; i < len(out0); i++ {
				buf[i] = registerObject(out0[i])
			}
			ret0.data = data
			ret0.length = C.int(len(out0))
		}
	}
	return ret0
}

//export World_Tx_World
func World_Tx_World(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.Tx](self)
	out0 := obj.World()
	ret0 := registerObject(out0)
	return ret0
}
