// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	world "github.com/df-mc/dragonfly/server/world"
	"unsafe"
)

//export World_EntityHandle_Ctor
func World_EntityHandle_Ctor() C.uint64_t {
	value := &world.EntityHandle{}
	return registerObject(value)
}

//export World_EntityHandle_Close
func World_EntityHandle_Close(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.EntityHandle](self)
	out0 := obj.Close()
	ret0 := registerObject(out0)
	return ret0
}

//export World_EntityHandle_Entity
func World_EntityHandle_Entity(self C.uint64_t, p1 C.uint64_t) C.World_EntityHandle_Entity_Result {
	obj := mustLoadHandle[*world.EntityHandle](self)
	out0, out1 := obj.Entity(mustLoadHandle[*world.Tx](p1))
	v0 := registerObject(out0)
	v1 := toCBool(out1)
	return C.World_EntityHandle_Entity_Result{
		v0: v0,
		v1: v1,
	}
}

//export World_EntityHandle_ExecWorld
func World_EntityHandle_ExecWorld(self C.uint64_t, p1 C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.EntityHandle](self)
	out0 := obj.ExecWorld(mustLoadHandle[func(*world.Tx, world.Entity)](p1))
	ret0 := toCBool(out0)
	return ret0
}

//export World_EntityHandle_Type
func World_EntityHandle_Type(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.EntityHandle](self)
	out0 := obj.Type()
	ret0 := registerObject(out0)
	return ret0
}

//export World_EntityHandle_UUID
func World_EntityHandle_UUID(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.EntityHandle](self)
	out0 := obj.UUID()
	ret0Slice := out0[:]
	var ret0ElemZero C.uint8_t
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.uint8_t)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.uint8_t(uint8(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}
