// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	world "github.com/df-mc/dragonfly/server/world"
)

//export World_SetOpts_Ctor
func World_SetOpts_Ctor() C.uint64_t {
	value := &world.SetOpts{}
	return registerObject(value)
}
