// Code generated by generator. DO NOT EDIT.
package output

/*
#include "interop_array.h"
*/
import "C"

import (
	cube "github.com/df-mc/dragonfly/server/block/cube"
	world "github.com/df-mc/dragonfly/server/world"
	uuid "github.com/google/uuid"
	time "time"
	"unsafe"
)

//export World_World_Ctor
func World_World_Ctor() C.uint64_t {
	value := &world.World{}
	return registerObject(value)
}

//export World_World_Close
func World_World_Close(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Close()
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_DefaultGameMode
func World_World_DefaultGameMode(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.DefaultGameMode()
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_Difficulty
func World_World_Difficulty(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Difficulty()
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_Dimension
func World_World_Dimension(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Dimension()
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_EntityRegistry
func World_World_EntityRegistry(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.EntityRegistry()
	ret0 := registerStructValue(out0)
	return ret0
}

//export World_World_Exec
func World_World_Exec(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Exec(mustLoadHandle[world.ExecFunc](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_Handle
func World_World_Handle(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.Handle(mustLoadHandle[world.Handler](p1))
}

//export World_World_Handler
func World_World_Handler(self C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Handler()
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_Name
func World_World_Name(self C.uint64_t) *C.char {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Name()
	ret0 := C.CString(out0)
	return ret0
}

//export World_World_PlayerSpawn
func World_World_PlayerSpawn(self C.uint64_t, p1 C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.PlayerSpawn(mustLoadHandle[uuid.UUID](p1))
	ret0Slice := out0[:]
	var ret0ElemZero C.int
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.int)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.int(int(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export World_World_PortalDestination
func World_World_PortalDestination(self C.uint64_t, p1 C.uint64_t) C.uint64_t {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.PortalDestination(mustLoadHandle[world.Dimension](p1))
	ret0 := registerObject(out0)
	return ret0
}

//export World_World_Range
func World_World_Range(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Range()
	ret0Slice := out0[:]
	var ret0ElemZero C.int
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.int)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.int(int(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export World_World_Save
func World_World_Save(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.Save()
}

//export World_World_SetDefaultGameMode
func World_World_SetDefaultGameMode(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetDefaultGameMode(mustLoadHandle[world.GameMode](p1))
}

//export World_World_SetDifficulty
func World_World_SetDifficulty(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetDifficulty(mustLoadHandle[world.Difficulty](p1))
}

//export World_World_SetPlayerSpawn
func World_World_SetPlayerSpawn(self C.uint64_t, p1 C.uint64_t, p2 C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetPlayerSpawn(mustLoadHandle[uuid.UUID](p1), mustLoadHandle[cube.Pos](p2))
}

//export World_World_SetRequiredSleepDuration
func World_World_SetRequiredSleepDuration(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetRequiredSleepDuration(time.Duration(int64(p1)))
}

//export World_World_SetSpawn
func World_World_SetSpawn(self C.uint64_t, p1 C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetSpawn(mustLoadHandle[cube.Pos](p1))
}

//export World_World_SetTickRange
func World_World_SetTickRange(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetTickRange(int(p1))
}

//export World_World_SetTime
func World_World_SetTime(self C.uint64_t, p1 C.int) {
	obj := mustLoadHandle[*world.World](self)
	obj.SetTime(int(p1))
}

//export World_World_Spawn
func World_World_Spawn(self C.uint64_t) C.GoArray {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Spawn()
	ret0Slice := out0[:]
	var ret0ElemZero C.int
	ret0ElemSize := C.int(unsafe.Sizeof(ret0ElemZero))
	ret0 := C.GoArray{data: nil, length: 0, elementSize: ret0ElemSize}
	if len(ret0Slice) > 0 {
		totalSize := C.size_t(len(ret0Slice)) * C.size_t(ret0ElemSize)
		data := C.malloc(totalSize)
		if data != nil {
			buf := unsafe.Slice((*C.int)(data), len(ret0Slice))
			for i := 0; i < len(ret0Slice); i++ {
				buf[i] = C.int(int(ret0Slice[i]))
			}
			ret0.data = data
			ret0.length = C.int(len(ret0Slice))
		}
	}
	return ret0
}

//export World_World_StartRaining
func World_World_StartRaining(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StartRaining(time.Duration(int64(p1)))
}

//export World_World_StartThundering
func World_World_StartThundering(self C.uint64_t, p1 C.int64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StartThundering(time.Duration(int64(p1)))
}

//export World_World_StartTime
func World_World_StartTime(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StartTime()
}

//export World_World_StartWeatherCycle
func World_World_StartWeatherCycle(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StartWeatherCycle()
}

//export World_World_StopRaining
func World_World_StopRaining(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StopRaining()
}

//export World_World_StopThundering
func World_World_StopThundering(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StopThundering()
}

//export World_World_StopTime
func World_World_StopTime(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StopTime()
}

//export World_World_StopWeatherCycle
func World_World_StopWeatherCycle(self C.uint64_t) {
	obj := mustLoadHandle[*world.World](self)
	obj.StopWeatherCycle()
}

//export World_World_Time
func World_World_Time(self C.uint64_t) C.int {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.Time()
	ret0 := C.int(int(out0))
	return ret0
}

//export World_World_TimeCycle
func World_World_TimeCycle(self C.uint64_t) C.bool {
	obj := mustLoadHandle[*world.World](self)
	out0 := obj.TimeCycle()
	ret0 := toCBool(out0)
	return ret0
}
