// Code generated by generator. DO NOT EDIT.
//go:build cgo

package plugin

/*
#include <stdint.h>
*/
import "C"

//export csharp_player_health
func csharp_player_health(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerHealth(uint64(playerID)))
}

//export csharp_set_player_health
func csharp_set_player_health(ctx C.uintptr_t, playerID C.uint64_t, health C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerHealth(uint64(playerID), float64(health)))
}

//export csharp_player_food
func csharp_player_food(ctx C.uintptr_t, playerID C.uint64_t) C.int32_t {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.int32_t(hostCtx.manager.PlayerFood(uint64(playerID)))
}

//export csharp_set_player_food
func csharp_set_player_food(ctx C.uintptr_t, playerID C.uint64_t, food C.int32_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerFood(uint64(playerID), int32(food)))
}

//export csharp_player_name
func csharp_player_name(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerName(uint64(playerID)))
}

//export csharp_player_game_mode
func csharp_player_game_mode(ctx C.uintptr_t, playerID C.uint64_t) C.int32_t {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.int32_t(hostCtx.manager.PlayerGameMode(uint64(playerID)))
}

//export csharp_set_player_game_mode
func csharp_set_player_game_mode(ctx C.uintptr_t, playerID C.uint64_t, mode C.int32_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerGameMode(uint64(playerID), int32(mode)))
}

//export csharp_player_xuid
func csharp_player_xuid(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerXUID(uint64(playerID)))
}

//export csharp_player_device_id
func csharp_player_device_id(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerDeviceID(uint64(playerID)))
}

//export csharp_player_device_model
func csharp_player_device_model(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerDeviceModel(uint64(playerID)))
}

//export csharp_player_self_signed_id
func csharp_player_self_signed_id(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerSelfSignedID(uint64(playerID)))
}

//export csharp_player_name_tag
func csharp_player_name_tag(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerNameTag(uint64(playerID)))
}

//export csharp_set_player_name_tag
func csharp_set_player_name_tag(ctx C.uintptr_t, playerID C.uint64_t, value *C.char) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerNameTag(uint64(playerID), GoCString(value)))
}

//export csharp_player_score_tag
func csharp_player_score_tag(ctx C.uintptr_t, playerID C.uint64_t) *C.char {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return CString("")
	}
	return CString(hostCtx.manager.PlayerScoreTag(uint64(playerID)))
}

//export csharp_set_player_score_tag
func csharp_set_player_score_tag(ctx C.uintptr_t, playerID C.uint64_t, value *C.char) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerScoreTag(uint64(playerID), GoCString(value)))
}

//export csharp_player_absorption
func csharp_player_absorption(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerAbsorption(uint64(playerID)))
}

//export csharp_set_player_absorption
func csharp_set_player_absorption(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerAbsorption(uint64(playerID), float64(value)))
}

//export csharp_player_max_health
func csharp_player_max_health(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerMaxHealth(uint64(playerID)))
}

//export csharp_set_player_max_health
func csharp_set_player_max_health(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerMaxHealth(uint64(playerID), float64(value)))
}

//export csharp_player_speed
func csharp_player_speed(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerSpeed(uint64(playerID)))
}

//export csharp_set_player_speed
func csharp_set_player_speed(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerSpeed(uint64(playerID), float64(value)))
}

//export csharp_player_flight_speed
func csharp_player_flight_speed(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerFlightSpeed(uint64(playerID)))
}

//export csharp_set_player_flight_speed
func csharp_set_player_flight_speed(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerFlightSpeed(uint64(playerID), float64(value)))
}

//export csharp_player_vertical_flight_speed
func csharp_player_vertical_flight_speed(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerVerticalFlightSpeed(uint64(playerID)))
}

//export csharp_set_player_vertical_flight_speed
func csharp_set_player_vertical_flight_speed(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerVerticalFlightSpeed(uint64(playerID), float64(value)))
}

//export csharp_player_experience
func csharp_player_experience(ctx C.uintptr_t, playerID C.uint64_t) C.int32_t {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.int32_t(hostCtx.manager.PlayerExperience(uint64(playerID)))
}

//export csharp_player_experience_level
func csharp_player_experience_level(ctx C.uintptr_t, playerID C.uint64_t) C.int32_t {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.int32_t(hostCtx.manager.PlayerExperienceLevel(uint64(playerID)))
}

//export csharp_set_player_experience_level
func csharp_set_player_experience_level(ctx C.uintptr_t, playerID C.uint64_t, value C.int32_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerExperienceLevel(uint64(playerID), int32(value)))
}

//export csharp_player_experience_progress
func csharp_player_experience_progress(ctx C.uintptr_t, playerID C.uint64_t) C.double {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.double(hostCtx.manager.PlayerExperienceProgress(uint64(playerID)))
}

//export csharp_set_player_experience_progress
func csharp_set_player_experience_progress(ctx C.uintptr_t, playerID C.uint64_t, value C.double) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerExperienceProgress(uint64(playerID), float64(value)))
}

//export csharp_player_on_ground
func csharp_player_on_ground(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerOnGround(uint64(playerID)))
}

//export csharp_player_sneaking
func csharp_player_sneaking(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerSneaking(uint64(playerID)))
}

//export csharp_set_player_sneaking
func csharp_set_player_sneaking(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerSneaking(uint64(playerID), value != 0))
}

//export csharp_player_sprinting
func csharp_player_sprinting(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerSprinting(uint64(playerID)))
}

//export csharp_set_player_sprinting
func csharp_set_player_sprinting(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerSprinting(uint64(playerID), value != 0))
}

//export csharp_player_swimming
func csharp_player_swimming(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerSwimming(uint64(playerID)))
}

//export csharp_set_player_swimming
func csharp_set_player_swimming(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerSwimming(uint64(playerID), value != 0))
}

//export csharp_player_flying
func csharp_player_flying(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerFlying(uint64(playerID)))
}

//export csharp_set_player_flying
func csharp_set_player_flying(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerFlying(uint64(playerID), value != 0))
}

//export csharp_player_gliding
func csharp_player_gliding(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerGliding(uint64(playerID)))
}

//export csharp_set_player_gliding
func csharp_set_player_gliding(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerGliding(uint64(playerID), value != 0))
}

//export csharp_player_crawling
func csharp_player_crawling(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerCrawling(uint64(playerID)))
}

//export csharp_set_player_crawling
func csharp_set_player_crawling(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerCrawling(uint64(playerID), value != 0))
}

//export csharp_player_using_item
func csharp_player_using_item(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerUsingItem(uint64(playerID)))
}

//export csharp_player_invisible
func csharp_player_invisible(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerInvisible(uint64(playerID)))
}

//export csharp_set_player_invisible
func csharp_set_player_invisible(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerInvisible(uint64(playerID), value != 0))
}

//export csharp_player_immobile
func csharp_player_immobile(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerImmobile(uint64(playerID)))
}

//export csharp_set_player_immobile
func csharp_set_player_immobile(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerImmobile(uint64(playerID), value != 0))
}

//export csharp_player_dead
func csharp_player_dead(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerDead(uint64(playerID)))
}

//export csharp_player_latency
func csharp_player_latency(ctx C.uintptr_t, playerID C.uint64_t) C.int64_t {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return C.int64_t(hostCtx.manager.PlayerLatency(uint64(playerID)).Milliseconds())
}

//export csharp_set_player_on_fire_millis
func csharp_set_player_on_fire_millis(ctx C.uintptr_t, playerID C.uint64_t, millis C.int64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerOnFireMillis(uint64(playerID), int64(millis)))
}

//export csharp_add_player_food
func csharp_add_player_food(ctx C.uintptr_t, playerID C.uint64_t, points C.int32_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.AddPlayerFood(uint64(playerID), int32(points)))
}

//export csharp_player_use_item
func csharp_player_use_item(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerUseItem(uint64(playerID)))
}

//export csharp_player_jump
func csharp_player_jump(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerJump(uint64(playerID)))
}

//export csharp_player_swing_arm
func csharp_player_swing_arm(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerSwingArm(uint64(playerID)))
}

//export csharp_player_wake
func csharp_player_wake(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerWake(uint64(playerID)))
}

//export csharp_player_extinguish
func csharp_player_extinguish(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerExtinguish(uint64(playerID)))
}

//export csharp_set_player_show_coordinates
func csharp_set_player_show_coordinates(ctx C.uintptr_t, playerID C.uint64_t, value C.int) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerShowCoordinates(uint64(playerID), value != 0))
}

//export csharp_set_player_held_slot
func csharp_set_player_held_slot(ctx C.uintptr_t, playerID C.uint64_t, slot C.int32_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.SetPlayerHeldSlot(uint64(playerID), int32(slot)))
}

//export csharp_player_move_items_to_inventory
func csharp_player_move_items_to_inventory(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerMoveItemsToInventory(uint64(playerID)))
}

//export csharp_player_close_form
func csharp_player_close_form(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerCloseForm(uint64(playerID)))
}

//export csharp_player_close_dialogue
func csharp_player_close_dialogue(ctx C.uintptr_t, playerID C.uint64_t) C.int {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return 0
	}
	return BoolInt(hostCtx.manager.PlayerCloseDialogue(uint64(playerID)))
}

//export csharp_player_message
func csharp_player_message(ctx C.uintptr_t, playerID C.uint64_t, message *C.char) {
	hostCtx, ok := CSharpHostContextByID(uintptr(ctx))
	if !ok || hostCtx.manager == nil {
		return
	}
	hostCtx.manager.PlayerMessage(uint64(playerID), GoCString(message))
}
