// Code generated by go generate; DO NOT EDIT.
package plugin

import "github.com/df-mc/dragonfly/server/player"

func (m *Manager) PlayerHealth(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.Health() })
}

func (m *Manager) PlayerFood(playerID uint64) int32 {
	return playerValue(m, playerID, int32(0), func(p *player.Player) int32 { return int32(p.Food()) })
}

func (m *Manager) SetPlayerFood(playerID uint64, food int32) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetFood(int(food)) })
}

func (m *Manager) PlayerName(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.Name() })
}

func (m *Manager) PlayerXUID(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.XUID() })
}

func (m *Manager) PlayerDeviceID(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.DeviceID() })
}

func (m *Manager) PlayerDeviceModel(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.DeviceModel() })
}

func (m *Manager) PlayerSelfSignedID(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.SelfSignedID() })
}

func (m *Manager) PlayerNameTag(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.NameTag() })
}

func (m *Manager) SetPlayerNameTag(playerID uint64, value string) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetNameTag(value) })
}

func (m *Manager) PlayerScoreTag(playerID uint64) string {
	return playerValue(m, playerID, "", func(p *player.Player) string { return p.ScoreTag() })
}

func (m *Manager) SetPlayerScoreTag(playerID uint64, value string) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetScoreTag(value) })
}

func (m *Manager) PlayerAbsorption(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.Absorption() })
}

func (m *Manager) SetPlayerAbsorption(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetAbsorption(value) })
}

func (m *Manager) PlayerMaxHealth(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.MaxHealth() })
}

func (m *Manager) SetPlayerMaxHealth(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetMaxHealth(value) })
}

func (m *Manager) PlayerSpeed(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.Speed() })
}

func (m *Manager) SetPlayerSpeed(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetSpeed(value) })
}

func (m *Manager) PlayerFlightSpeed(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.FlightSpeed() })
}

func (m *Manager) SetPlayerFlightSpeed(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetFlightSpeed(value) })
}

func (m *Manager) PlayerVerticalFlightSpeed(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.VerticalFlightSpeed() })
}

func (m *Manager) SetPlayerVerticalFlightSpeed(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetVerticalFlightSpeed(value) })
}

func (m *Manager) PlayerExperience(playerID uint64) int32 {
	return playerValue(m, playerID, int32(0), func(p *player.Player) int32 { return int32(p.Experience()) })
}

func (m *Manager) PlayerExperienceLevel(playerID uint64) int32 {
	return playerValue(m, playerID, int32(0), func(p *player.Player) int32 { return int32(p.ExperienceLevel()) })
}

func (m *Manager) SetPlayerExperienceLevel(playerID uint64, value int32) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetExperienceLevel(int(value)) })
}

func (m *Manager) PlayerExperienceProgress(playerID uint64) float64 {
	return playerValue(m, playerID, float64(0), func(p *player.Player) float64 { return p.ExperienceProgress() })
}

func (m *Manager) SetPlayerExperienceProgress(playerID uint64, value float64) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.SetExperienceProgress(value) })
}

func (m *Manager) PlayerOnGround(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.OnGround() })
}

func (m *Manager) PlayerSneaking(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Sneaking() })
}

func (m *Manager) SetPlayerSneaking(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartSneaking, (*player.Player).StopSneaking)
}

func (m *Manager) PlayerSprinting(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Sprinting() })
}

func (m *Manager) SetPlayerSprinting(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartSprinting, (*player.Player).StopSprinting)
}

func (m *Manager) PlayerSwimming(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Swimming() })
}

func (m *Manager) SetPlayerSwimming(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartSwimming, (*player.Player).StopSwimming)
}

func (m *Manager) PlayerFlying(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Flying() })
}

func (m *Manager) SetPlayerFlying(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartFlying, (*player.Player).StopFlying)
}

func (m *Manager) PlayerGliding(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Gliding() })
}

func (m *Manager) SetPlayerGliding(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartGliding, (*player.Player).StopGliding)
}

func (m *Manager) PlayerCrawling(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Crawling() })
}

func (m *Manager) SetPlayerCrawling(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).StartCrawling, (*player.Player).StopCrawling)
}

func (m *Manager) PlayerUsingItem(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.UsingItem() })
}

func (m *Manager) PlayerInvisible(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Invisible() })
}

func (m *Manager) SetPlayerInvisible(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).SetInvisible, (*player.Player).SetVisible)
}

func (m *Manager) PlayerImmobile(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Immobile() })
}

func (m *Manager) SetPlayerImmobile(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).SetImmobile, (*player.Player).SetMobile)
}

func (m *Manager) PlayerDead(playerID uint64) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.Dead() })
}

func (m *Manager) AddPlayerFood(playerID uint64, points int32) bool {
	return m.playerUpdate(playerID, func(p *player.Player) { p.AddFood(int(points)) })
}

func (m *Manager) PlayerUseItem(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).UseItem)
}

func (m *Manager) PlayerJump(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).Jump)
}

func (m *Manager) PlayerSwingArm(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).SwingArm)
}

func (m *Manager) PlayerWake(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).Wake)
}

func (m *Manager) PlayerExtinguish(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).Extinguish)
}

func (m *Manager) SetPlayerShowCoordinates(playerID uint64, value bool) bool {
	return m.playerToggle(playerID, value, (*player.Player).ShowCoordinates, (*player.Player).HideCoordinates)
}

func (m *Manager) PlayerMainHandItem(playerID uint64) ItemStackData {
	return playerValue(m, playerID, ItemStackData{}, func(p *player.Player) ItemStackData { return mainHandItemData(p) })
}

func (m *Manager) SetPlayerMainHandItem(playerID uint64, stack ItemStackData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return setMainHandItemData(p, stack) })
}

func (m *Manager) PlayerOffHandItem(playerID uint64) ItemStackData {
	return playerValue(m, playerID, ItemStackData{}, func(p *player.Player) ItemStackData { return offHandItemData(p) })
}

func (m *Manager) SetPlayerOffHandItem(playerID uint64, stack ItemStackData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return setOffHandItemData(p, stack) })
}

func (m *Manager) PlayerInventoryItems(playerID uint64) []ItemStackData {
	return playerValue(m, playerID, nil, func(p *player.Player) []ItemStackData { return inventoryItemsData(p.Inventory()) })
}

func (m *Manager) SetPlayerInventoryItems(playerID uint64, items []ItemStackData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return setInventoryItemsData(p.Inventory(), items) })
}

func (m *Manager) PlayerEnderChestItems(playerID uint64) []ItemStackData {
	return playerValue(m, playerID, nil, func(p *player.Player) []ItemStackData { return inventoryItemsData(p.EnderChestInventory()) })
}

func (m *Manager) SetPlayerEnderChestItems(playerID uint64, items []ItemStackData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return setInventoryItemsData(p.EnderChestInventory(), items) })
}

func (m *Manager) PlayerArmourItems(playerID uint64) []ItemStackData {
	return playerValue(m, playerID, nil, func(p *player.Player) []ItemStackData { return armourItemsData(p.Armour()) })
}

func (m *Manager) SetPlayerArmourItems(playerID uint64, items []ItemStackData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return setArmourItemsData(p.Armour(), items) })
}

func (m *Manager) SetPlayerHeldSlot(playerID uint64, slot int32) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return p.SetHeldSlot(int(slot)) == nil })
}

func (m *Manager) PlayerMoveItemsToInventory(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).MoveItemsToInventory)
}

func (m *Manager) PlayerCloseForm(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).CloseForm)
}

func (m *Manager) PlayerCloseDialogue(playerID uint64) bool {
	return m.playerUpdate(playerID, (*player.Player).CloseDialogue)
}

func (m *Manager) PlayerSendMenuForm(playerID uint64, value MenuFormData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return sendMenuFormData(p, value) })
}

func (m *Manager) PlayerSendModalForm(playerID uint64, value ModalFormData) bool {
	return playerValue(m, playerID, false, func(p *player.Player) bool { return sendModalFormData(p, value) })
}

func (m *Manager) PlayerMessage(playerID uint64, message string) {
	_ = m.playerUpdate(playerID, func(p *player.Player) { p.Message(message) })
}
