package generator

import (
	"bytes"
	"fmt"
	"go/constant"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const csharpGeneratedBanner = "// Code generated by generator. DO NOT EDIT."

type CSharpSDKConfig struct {
	PackageDir      string
	Namespace       string
	OutputDir       string
	HostInterface   string
	Wrappers        []CSharpWrapperConfig
	ExtraModelTypes []string
}

type CSharpWrapperConfig struct {
	GoType     string
	ClassName  string
	HostPrefix string
}

type sdkPackage struct {
	pkg         *packages.Package
	namedByName map[string]*types.Named
	constByType map[string][]enumValue
}

type enumValue struct {
	GoName    string
	CSName    string
	ValueExpr string
}

type hostMethod struct {
	Name string
	Sig  *types.Signature
}

type wrapperMethod struct {
	Name string
	Func *types.Func
	Sig  *types.Signature
}

type typeSet map[string]*types.Named

func (s typeSet) add(named *types.Named) {
	if named == nil {
		return
	}
	obj := named.Obj()
	if obj == nil {
		return
	}
	k := obj.Name()
	if k == "" {
		return
	}
	if _, ok := s[k]; ok {
		return
	}
	s[k] = named
}

func GenerateCSharpSDK(cfg CSharpSDKConfig) error {
	if strings.TrimSpace(cfg.PackageDir) == "" {
		return fmt.Errorf("generator: CSharpSDKConfig.PackageDir is required")
	}
	if strings.TrimSpace(cfg.Namespace) == "" {
		return fmt.Errorf("generator: CSharpSDKConfig.Namespace is required")
	}
	if strings.TrimSpace(cfg.OutputDir) == "" {
		return fmt.Errorf("generator: CSharpSDKConfig.OutputDir is required")
	}
	if strings.TrimSpace(cfg.HostInterface) == "" {
		return fmt.Errorf("generator: CSharpSDKConfig.HostInterface is required")
	}

	loaded, err := loadSDKPackage(cfg.PackageDir)
	if err != nil {
		return err
	}

	hostNamed := loaded.namedByName[cfg.HostInterface]
	if hostNamed == nil {
		return fmt.Errorf("generator: host interface %q not found in %s", cfg.HostInterface, cfg.PackageDir)
	}
	hostIface, ok := hostNamed.Underlying().(*types.Interface)
	if !ok {
		return fmt.Errorf("generator: %q is not an interface", cfg.HostInterface)
	}
	hostIface = hostIface.Complete()
	hostMethods := flattenInterfaceMethods(hostIface)
	hostByName := make(map[string]hostMethod, len(hostMethods))
	for _, method := range hostMethods {
		hostByName[method.Name] = method
	}

	modelTypes := typeSet{}
	for _, extra := range cfg.ExtraModelTypes {
		named := loaded.namedByName[extra]
		if named == nil {
			return fmt.Errorf("generator: extra model type %q not found", extra)
		}
		collectNamedTypes(named, loaded.pkg.Types, modelTypes)
	}

	for _, method := range hostMethods {
		sig := method.Sig
		for i := 0; i < sig.Params().Len(); i++ {
			collectNamedTypes(sig.Params().At(i).Type(), loaded.pkg.Types, modelTypes)
		}
		ret := signatureReturnForCSharp(sig)
		if ret != nil {
			collectNamedTypes(ret, loaded.pkg.Types, modelTypes)
		}
	}

	wrappers := make([]wrapperRenderSpec, 0, len(cfg.Wrappers))
	for _, wrapperCfg := range cfg.Wrappers {
		spec, err := buildWrapperSpec(loaded, wrapperCfg, hostByName)
		if err != nil {
			return err
		}
		wrappers = append(wrappers, spec)
		for _, method := range spec.Methods {
			for _, p := range method.GoParams {
				collectNamedTypes(p, loaded.pkg.Types, modelTypes)
			}
			if method.GoReturn != nil {
				collectNamedTypes(method.GoReturn, loaded.pkg.Types, modelTypes)
			}
		}
	}

	for _, wrapperCfg := range cfg.Wrappers {
		delete(modelTypes, wrapperCfg.GoType)
	}
	delete(modelTypes, cfg.HostInterface)

	if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
		return err
	}
	if err := cleanGeneratedCSharpSDKFiles(cfg.OutputDir); err != nil {
		return err
	}

	modelsPath := filepath.Join(cfg.OutputDir, "Models.g.cs")
	if err := os.WriteFile(modelsPath, []byte(renderCSharpModels(cfg.Namespace, loaded, modelTypes)), 0o644); err != nil {
		return err
	}

	hostPath := filepath.Join(cfg.OutputDir, "Host.g.cs")
	if err := os.WriteFile(hostPath, []byte(renderCSharpHost(cfg.Namespace, hostMethods)), 0o644); err != nil {
		return err
	}

	for _, wrapper := range wrappers {
		wrapperPath := filepath.Join(cfg.OutputDir, wrapper.ClassName+".g.cs")
		if err := os.WriteFile(wrapperPath, []byte(renderCSharpWrapper(cfg.Namespace, wrapper)), 0o644); err != nil {
			return err
		}
	}

	return nil
}

func cleanGeneratedCSharpSDKFiles(outputDir string) error {
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".g.cs") {
			continue
		}
		path := filepath.Join(outputDir, name)
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if !bytes.Contains(data, []byte(csharpGeneratedBanner)) {
			continue
		}
		if removeErr := os.Remove(path); removeErr != nil && !os.IsNotExist(removeErr) {
			return removeErr
		}
	}
	return nil
}

func loadSDKPackage(packageDir string) (*sdkPackage, error) {
	abs, err := filepath.Abs(packageDir)
	if err != nil {
		return nil, err
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedSyntax |
			packages.NeedModule,
		Dir: abs,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("generator: expected exactly one package in %s, got %d", abs, len(pkgs))
	}
	if n := packages.PrintErrors(pkgs); n > 0 {
		return nil, fmt.Errorf("generator: package load reported %d errors", n)
	}

	pkg := pkgs[0]
	if pkg.Types == nil {
		return nil, fmt.Errorf("generator: package %s has no type information", pkg.PkgPath)
	}

	namedByName := map[string]*types.Named{}
	scope := pkg.Types.Scope()
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		tname, ok := obj.(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := tname.Type().(*types.Named)
		if !ok {
			continue
		}
		namedByName[tname.Name()] = named
	}

	constByType := map[string][]enumValue{}
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		c, ok := obj.(*types.Const)
		if !ok {
			continue
		}
		named, ok := c.Type().(*types.Named)
		if !ok {
			continue
		}
		if named.Obj() == nil || named.Obj().Pkg() != pkg.Types {
			continue
		}
		basic, ok := named.Underlying().(*types.Basic)
		if !ok || (basic.Info()&types.IsInteger) == 0 {
			continue
		}
		valueExpr := enumValueExpr(c.Val())
		if valueExpr == "" {
			continue
		}
		typeName := named.Obj().Name()
		constByType[typeName] = append(constByType[typeName], enumValue{
			GoName:    c.Name(),
			CSName:    enumMemberName(typeName, c.Name()),
			ValueExpr: valueExpr,
		})
	}

	for typeName := range constByType {
		sort.Slice(constByType[typeName], func(i, j int) bool {
			return constByType[typeName][i].GoName < constByType[typeName][j].GoName
		})
	}

	return &sdkPackage{
		pkg:         pkg,
		namedByName: namedByName,
		constByType: constByType,
	}, nil
}

func enumValueExpr(v constant.Value) string {
	if v == nil {
		return ""
	}
	switch v.Kind() {
	case constant.Int:
		return v.ExactString()
	default:
		return ""
	}
}

func enumMemberName(typeName, constName string) string {
	candidates := []string{typeName}
	if strings.HasSuffix(typeName, "Kind") {
		candidates = append(candidates, strings.TrimSuffix(typeName, "Kind"))
	}

	member := constName
	for _, prefix := range candidates {
		if prefix == "" {
			continue
		}
		if strings.HasPrefix(member, prefix) {
			member = strings.TrimPrefix(member, prefix)
			break
		}
	}
	if member == "" {
		member = constName
	}
	return csharpIdentifier(member)
}

func flattenInterfaceMethods(iface *types.Interface) []hostMethod {
	count := iface.NumMethods()
	methods := make([]hostMethod, 0, count)
	for i := 0; i < count; i++ {
		m := iface.Method(i)
		methods = append(methods, hostMethod{Name: m.Name(), Sig: m.Type().(*types.Signature)})
	}
	sort.Slice(methods, func(i, j int) bool {
		return methods[i].Name < methods[j].Name
	})
	return methods
}

func signatureReturnForCSharp(sig *types.Signature) types.Type {
	results := sig.Results()
	switch results.Len() {
	case 0:
		return nil
	case 1:
		return results.At(0).Type()
	case 2:
		if isErrorType(results.At(1).Type()) {
			return results.At(0).Type()
		}
	}
	return nil
}

func isErrorType(t types.Type) bool {
	if t == nil {
		return false
	}
	errType := types.Universe.Lookup("error").Type()
	return types.Identical(t, errType)
}

func collectNamedTypes(t types.Type, owner *types.Package, out typeSet) {
	if t == nil {
		return
	}

	switch tt := t.(type) {
	case *types.Pointer:
		collectNamedTypes(tt.Elem(), owner, out)
		return
	case *types.Slice:
		collectNamedTypes(tt.Elem(), owner, out)
		return
	case *types.Array:
		collectNamedTypes(tt.Elem(), owner, out)
		return
	case *types.Map:
		collectNamedTypes(tt.Key(), owner, out)
		collectNamedTypes(tt.Elem(), owner, out)
		return
	case *types.Named:
		obj := tt.Obj()
		if obj == nil {
			return
		}
		if obj.Pkg() != owner {
			return
		}
		if !obj.Exported() {
			return
		}
		if _, ok := out[obj.Name()]; ok {
			return
		}
		out.add(tt)
		under := tt.Underlying()
		if st, ok := under.(*types.Struct); ok {
			for i := 0; i < st.NumFields(); i++ {
				f := st.Field(i)
				if !f.Exported() {
					continue
				}
				collectNamedTypes(f.Type(), owner, out)
			}
		}
		return
	}
}

type wrapperRenderSpec struct {
	GoType    string
	ClassName string
	Methods   []wrapperRenderMethod
}

type wrapperRenderMethod struct {
	Name         string
	CSName       string
	GoParams     []types.Type
	CSParams     []wrapperParam
	GoReturn     types.Type
	CSReturnType string
	Body         string
}

type wrapperParam struct {
	Name string
	Type string
}

func buildWrapperSpec(loaded *sdkPackage, cfg CSharpWrapperConfig, hostByName map[string]hostMethod) (wrapperRenderSpec, error) {
	named := loaded.namedByName[cfg.GoType]
	if named == nil {
		return wrapperRenderSpec{}, fmt.Errorf("generator: wrapper type %q not found", cfg.GoType)
	}

	className := strings.TrimSpace(cfg.ClassName)
	if className == "" {
		className = cfg.GoType
	}
	hostPrefix := strings.TrimSpace(cfg.HostPrefix)
	if hostPrefix == "" {
		hostPrefix = strings.TrimSuffix(cfg.GoType, "Ref")
		if hostPrefix == "" {
			hostPrefix = cfg.GoType
		}
	}

	methods := exportedMethodsOfNamed(named)
	out := wrapperRenderSpec{GoType: cfg.GoType, ClassName: className, Methods: make([]wrapperRenderMethod, 0, len(methods))}

	for _, method := range methods {
		if method.Name == "ID" {
			continue
		}

		sig := method.Sig
		params := make([]wrapperParam, 0, sig.Params().Len())
		goParams := make([]types.Type, 0, sig.Params().Len())
		for i := 0; i < sig.Params().Len(); i++ {
			p := sig.Params().At(i)
			goParams = append(goParams, p.Type())
			paramName := p.Name()
			if paramName == "" {
				paramName = fmt.Sprintf("p%d", i+1)
			}
			paramType := csharpTypeFor(p.Type(), typeContextParameter)
			if sig.Variadic() && i == sig.Params().Len()-1 {
				elem := p.Type().(*types.Slice).Elem()
				paramType = "params " + csharpTypeFor(elem, typeContextParameter) + "[]"
			}
			params = append(params, wrapperParam{Name: csharpParameterName(paramName), Type: paramType})
		}

		ret := signatureReturnForCSharp(sig)
		csReturn := "void"
		if ret != nil {
			csReturn = csharpTypeFor(ret, typeContextReturn)
		}

		methodCSName := csharpIdentifier(method.Name)
		body, err := buildWrapperMethodBody(method, params, ret, hostPrefix, hostByName)
		if err != nil {
			return wrapperRenderSpec{}, fmt.Errorf("generator: wrapper %s.%s: %w", cfg.GoType, method.Name, err)
		}

		out.Methods = append(out.Methods, wrapperRenderMethod{
			Name:         method.Name,
			CSName:       methodCSName,
			GoParams:     goParams,
			CSParams:     params,
			GoReturn:     ret,
			CSReturnType: csReturn,
			Body:         body,
		})
	}

	sort.Slice(out.Methods, func(i, j int) bool {
		return out.Methods[i].CSName < out.Methods[j].CSName
	})

	return out, nil
}

func exportedMethodsOfNamed(named *types.Named) []wrapperMethod {
	methodMap := map[string]wrapperMethod{}
	addMethodSet := func(set *types.MethodSet) {
		for i := 0; i < set.Len(); i++ {
			sel := set.At(i)
			fn, ok := sel.Obj().(*types.Func)
			if !ok || !fn.Exported() {
				continue
			}
			sig, ok := fn.Type().(*types.Signature)
			if !ok {
				continue
			}
			methodMap[fn.Name()] = wrapperMethod{Name: fn.Name(), Func: fn, Sig: sig}
		}
	}

	addMethodSet(types.NewMethodSet(named))
	addMethodSet(types.NewMethodSet(types.NewPointer(named)))

	out := make([]wrapperMethod, 0, len(methodMap))
	for _, method := range methodMap {
		out = append(out, method)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Name < out[j].Name
	})
	return out
}

func buildWrapperMethodBody(method wrapperMethod, params []wrapperParam, ret types.Type, hostPrefix string, hostByName map[string]hostMethod) (string, error) {
	if method.Sig.Variadic() {
		if method.Name == "Messagef" && len(params) == 2 {
			return "Message(TextFormat.Colourf(format, a));", nil
		}
		return "", fmt.Errorf("variadic methods are only supported for Messagef")
	}

	hostMethod, hostName, ok := resolveHostMethod(method, ret, hostPrefix, hostByName)
	if !ok {
		return "", fmt.Errorf("no host method mapping found")
	}

	if hostMethod.Sig.Params().Len() != method.Sig.Params().Len()+1 {
		return "", fmt.Errorf("mapped host method %s has incompatible parameter count", hostName)
	}

	if !isUInt64Type(hostMethod.Sig.Params().At(0).Type()) {
		return "", fmt.Errorf("mapped host method %s first parameter must be uint64", hostName)
	}

	callArgs := make([]string, 0, len(params)+1)
	callArgs = append(callArgs, "Id")

	for i := 0; i < method.Sig.Params().Len(); i++ {
		fromType := method.Sig.Params().At(i).Type()
		toType := hostMethod.Sig.Params().At(i + 1).Type()
		if !isTypeConvertible(fromType, toType) {
			return "", fmt.Errorf("parameter %d cannot convert from %s to %s", i, fromType.String(), toType.String())
		}
		expr := convertExpression(params[i].Name, fromType, toType)
		callArgs = append(callArgs, expr)
	}

	call := fmt.Sprintf("_host.%s(%s)", hostName, strings.Join(callArgs, ", "))
	if ret == nil {
		return call + ";", nil
	}

	hostRet := signatureReturnForCSharp(hostMethod.Sig)
	if hostRet == nil {
		return "", fmt.Errorf("mapped host method %s does not return a value", hostName)
	}
	if !isTypeConvertible(hostRet, ret) {
		return "", fmt.Errorf("return cannot convert from %s to %s", hostRet.String(), ret.String())
	}

	if isDurationType(ret) && !isDurationType(hostRet) && isSignedIntegerType(hostRet) {
		return fmt.Sprintf("return TimeSpan.FromMilliseconds(Math.Max(0L, %s));", call), nil
	}

	retExpr := convertExpression("result", hostRet, ret)
	if retExpr == "result" {
		return fmt.Sprintf("return %s;", call), nil
	}
	return fmt.Sprintf("return %s;", strings.ReplaceAll(retExpr, "result", call)), nil
}

func resolveHostMethod(method wrapperMethod, ret types.Type, hostPrefix string, hostByName map[string]hostMethod) (hostMethod, string, bool) {
	name := method.Name
	candidates := []string{}
	switch {
	case strings.HasPrefix(name, "Set"):
		candidates = append(candidates, "Set"+hostPrefix+strings.TrimPrefix(name, "Set"))
	case strings.HasPrefix(name, "Add"):
		candidates = append(candidates, "Add"+hostPrefix+strings.TrimPrefix(name, "Add"))
	default:
		candidates = append(candidates, hostPrefix+name)
	}
	if isDurationType(ret) && method.Sig.Params().Len() == 0 {
		candidates = append(candidates, hostPrefix+name+"Millis")
	}

	for _, candidate := range candidates {
		if hm, ok := hostByName[candidate]; ok {
			return hm, candidate, true
		}
	}
	return hostMethod{}, "", false
}

func isUInt64Type(t types.Type) bool {
	b, ok := underlyingBasic(t)
	if !ok {
		return false
	}
	return b.Kind() == types.Uint64
}

func isDurationType(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok || named.Obj() == nil || named.Obj().Pkg() == nil {
		return false
	}
	return named.Obj().Pkg().Path() == "time" && named.Obj().Name() == "Duration"
}

func isTypeConvertible(from, to types.Type) bool {
	if types.Identical(from, to) {
		return true
	}
	if isDurationType(from) && isSignedIntegerType(to) {
		return true
	}
	if isDurationType(to) && isSignedIntegerType(from) {
		return true
	}

	fromBasic, fromBasicOK := underlyingBasic(from)
	toBasic, toBasicOK := underlyingBasic(to)
	if fromBasicOK && toBasicOK {
		if (fromBasic.Info()&types.IsNumeric) != 0 && (toBasic.Info()&types.IsNumeric) != 0 {
			return true
		}
		if (fromBasic.Info()&types.IsBoolean) != 0 && (toBasic.Info()&types.IsBoolean) != 0 {
			return true
		}
		if (fromBasic.Info()&types.IsString) != 0 && (toBasic.Info()&types.IsString) != 0 {
			return true
		}
	}

	fromSlice, fromIsSlice := from.Underlying().(*types.Slice)
	toSlice, toIsSlice := to.Underlying().(*types.Slice)
	if fromIsSlice && toIsSlice {
		return isTypeConvertible(fromSlice.Elem(), toSlice.Elem())
	}

	fromArray, fromIsArray := from.Underlying().(*types.Array)
	toArray, toIsArray := to.Underlying().(*types.Array)
	if fromIsArray && toIsArray {
		return fromArray.Len() == toArray.Len() && isTypeConvertible(fromArray.Elem(), toArray.Elem())
	}

	fromMap, fromIsMap := from.Underlying().(*types.Map)
	toMap, toIsMap := to.Underlying().(*types.Map)
	if fromIsMap && toIsMap {
		return isTypeConvertible(fromMap.Key(), toMap.Key()) && isTypeConvertible(fromMap.Elem(), toMap.Elem())
	}

	return false
}

func underlyingBasic(t types.Type) (*types.Basic, bool) {
	switch tt := t.(type) {
	case *types.Basic:
		return tt, true
	case *types.Named:
		b, ok := tt.Underlying().(*types.Basic)
		return b, ok
	default:
		return nil, false
	}
}

func isSignedIntegerType(t types.Type) bool {
	b, ok := underlyingBasic(t)
	if !ok {
		return false
	}
	return b.Kind() == types.Int || b.Kind() == types.Int8 || b.Kind() == types.Int16 || b.Kind() == types.Int32 || b.Kind() == types.Int64
}

func convertExpression(expr string, from, to types.Type) string {
	if types.Identical(from, to) {
		return expr
	}
	if isDurationType(from) && isSignedIntegerType(to) {
		return fmt.Sprintf("(long)Math.Round(%s.TotalMilliseconds, MidpointRounding.AwayFromZero)", expr)
	}
	if isDurationType(to) && isSignedIntegerType(from) {
		return fmt.Sprintf("TimeSpan.FromMilliseconds(Math.Max(0L, %s))", expr)
	}

	fromBasic, fromBasicOK := underlyingBasic(from)
	toBasic, toBasicOK := underlyingBasic(to)
	if fromBasicOK && toBasicOK {
		if (fromBasic.Info()&types.IsNumeric) != 0 && (toBasic.Info()&types.IsNumeric) != 0 {
			return fmt.Sprintf("(%s)%s", csharpTypeFor(to, typeContextParameter), expr)
		}
	}

	return expr
}

type typeContext int

const (
	typeContextParameter typeContext = iota
	typeContextReturn
	typeContextField
)

func csharpTypeFor(t types.Type, ctx typeContext) string {
	if t == nil {
		return "void"
	}

	if isDurationType(t) {
		return "TimeSpan"
	}

	switch tt := t.(type) {
	case *types.Pointer:
		return csharpTypeFor(tt.Elem(), ctx)
	case *types.Named:
		obj := tt.Obj()
		if obj != nil && obj.Pkg() != nil && obj.Pkg().Name() == "guest" {
			if _, ok := tt.Underlying().(*types.Struct); ok {
				return csharpIdentifier(obj.Name())
			}
			if basic, ok := tt.Underlying().(*types.Basic); ok {
				if basic.Info()&types.IsInteger != 0 {
					return csharpIdentifier(obj.Name())
				}
			}
		}
		return csharpTypeFor(tt.Underlying(), ctx)
	case *types.Basic:
		switch tt.Kind() {
		case types.Bool:
			return "bool"
		case types.String:
			return "string"
		case types.Int, types.Int8, types.Int16, types.Int32:
			return "int"
		case types.Int64:
			return "long"
		case types.Uint, types.Uint8, types.Uint16, types.Uint32:
			return "uint"
		case types.Uint64, types.Uintptr:
			return "ulong"
		case types.Float32:
			return "float"
		case types.Float64:
			return "double"
		case types.UntypedNil:
			return "object?"
		default:
			return "object"
		}
	case *types.Slice:
		elem := csharpTypeFor(tt.Elem(), ctx)
		return "IReadOnlyList<" + elem + ">"
	case *types.Array:
		elem := csharpTypeFor(tt.Elem(), ctx)
		return "IReadOnlyList<" + elem + ">"
	case *types.Map:
		key := csharpTypeFor(tt.Key(), ctx)
		val := csharpTypeFor(tt.Elem(), ctx)
		return "IReadOnlyDictionary<" + key + ", " + val + ">"
	case *types.Interface:
		if isErrorType(tt) {
			return "Exception"
		}
		return "object"
	default:
		return "object"
	}
}

func renderCSharpModels(namespace string, loaded *sdkPackage, models typeSet) string {
	names := make([]string, 0, len(models))
	for name := range models {
		names = append(names, name)
	}
	sort.Strings(names)

	var out strings.Builder
	out.WriteString(csharpGeneratedBanner)
	out.WriteString("\n")
	out.WriteString("using System;\n")
	out.WriteString("using System.Collections.Generic;\n\n")
	out.WriteString("namespace ")
	out.WriteString(namespace)
	out.WriteString(";\n\n")

	for _, name := range names {
		named := models[name]
		if named == nil || named.Obj() == nil {
			continue
		}

		if values := loaded.constByType[name]; len(values) > 0 {
			baseType := csharpEnumBaseType(named)
			out.WriteString("public enum ")
			out.WriteString(csharpIdentifier(name))
			if baseType != "int" {
				out.WriteString(" : ")
				out.WriteString(baseType)
			}
			out.WriteString("\n{\n")
			for _, v := range values {
				out.WriteString("    ")
				out.WriteString(v.CSName)
				out.WriteString(" = ")
				out.WriteString(v.ValueExpr)
				out.WriteString(",\n")
			}
			out.WriteString("}\n\n")
			continue
		}

		st, ok := named.Underlying().(*types.Struct)
		if !ok {
			continue
		}

		fields := make([]string, 0, st.NumFields())
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if !f.Exported() {
				continue
			}
			fieldType := csharpTypeFor(f.Type(), typeContextField)
			fieldName := csharpIdentifier(f.Name())
			fields = append(fields, fieldType+" "+fieldName)
		}

		out.WriteString("public sealed partial record ")
		out.WriteString(csharpIdentifier(name))
		out.WriteString("(")
		out.WriteString(strings.Join(fields, ", "))
		out.WriteString(");\n\n")
	}

	return out.String()
}

func csharpEnumBaseType(named *types.Named) string {
	b, ok := named.Underlying().(*types.Basic)
	if !ok {
		return "int"
	}
	switch b.Kind() {
	case types.Int8:
		return "sbyte"
	case types.Int16:
		return "short"
	case types.Int32, types.Int:
		return "int"
	case types.Int64:
		return "long"
	case types.Uint8:
		return "byte"
	case types.Uint16:
		return "ushort"
	case types.Uint32, types.Uint:
		return "uint"
	case types.Uint64, types.Uintptr:
		return "ulong"
	default:
		return "int"
	}
}

func renderCSharpHost(namespace string, methods []hostMethod) string {
	var out strings.Builder
	out.WriteString(csharpGeneratedBanner)
	out.WriteString("\n")
	out.WriteString("using System.Collections.Generic;\n\n")
	out.WriteString("namespace ")
	out.WriteString(namespace)
	out.WriteString(";\n\n")
	out.WriteString("public interface IGuestHost\n{\n")

	for _, method := range methods {
		sig := method.Sig
		ret := signatureReturnForCSharp(sig)
		if sig.Results().Len() > 1 && ret == nil {
			continue
		}

		params := make([]string, 0, sig.Params().Len())
		for i := 0; i < sig.Params().Len(); i++ {
			p := sig.Params().At(i)
			name := csharpParameterName(p.Name())
			if name == "" {
				name = fmt.Sprintf("p%d", i+1)
			}
			params = append(params, csharpTypeFor(p.Type(), typeContextParameter)+" "+name)
		}

		retType := "void"
		if ret != nil {
			retType = csharpTypeFor(ret, typeContextReturn)
		}

		out.WriteString("    ")
		out.WriteString(retType)
		out.WriteString(" ")
		out.WriteString(method.Name)
		out.WriteString("(")
		out.WriteString(strings.Join(params, ", "))
		out.WriteString(");\n\n")
	}

	out.WriteString("}\n")
	return out.String()
}

func renderCSharpWrapper(namespace string, wrapper wrapperRenderSpec) string {
	var out strings.Builder
	out.WriteString(csharpGeneratedBanner)
	out.WriteString("\n")
	out.WriteString("using System;\n")
	out.WriteString("using System.Collections.Generic;\n\n")
	out.WriteString("namespace ")
	out.WriteString(namespace)
	out.WriteString(";\n\n")

	out.WriteString("public sealed partial class ")
	out.WriteString(csharpIdentifier(wrapper.ClassName))
	out.WriteString("\n{\n")
	out.WriteString("    private readonly IGuestHost _host;\n\n")
	out.WriteString("    internal ")
	out.WriteString(csharpIdentifier(wrapper.ClassName))
	out.WriteString("(IGuestHost host, ulong id)\n")
	out.WriteString("    {\n")
	out.WriteString("        _host = host ?? throw new ArgumentNullException(nameof(host));\n")
	out.WriteString("        Id = id;\n")
	out.WriteString("    }\n\n")
	out.WriteString("    public ulong Id { get; }\n\n")

	out.WriteString("    private T HostValue<T>(T fallback, Func<IGuestHost, T> fn)\n")
	out.WriteString("    {\n")
	out.WriteString("        if (Id == 0)\n")
	out.WriteString("        {\n")
	out.WriteString("            return fallback;\n")
	out.WriteString("        }\n")
	out.WriteString("        return fn(_host);\n")
	out.WriteString("    }\n\n")

	out.WriteString("    private bool HostBool(Func<IGuestHost, bool> fn)\n")
	out.WriteString("    {\n")
	out.WriteString("        return HostValue(false, fn);\n")
	out.WriteString("    }\n\n")

	out.WriteString("    private void HostDo(Action<IGuestHost> fn)\n")
	out.WriteString("    {\n")
	out.WriteString("        if (Id == 0)\n")
	out.WriteString("        {\n")
	out.WriteString("            return;\n")
	out.WriteString("        }\n")
	out.WriteString("        fn(_host);\n")
	out.WriteString("    }\n\n")

	for _, method := range wrapper.Methods {
		params := make([]string, 0, len(method.CSParams))
		for _, p := range method.CSParams {
			params = append(params, p.Type+" "+p.Name)
		}

		out.WriteString("    public ")
		out.WriteString(method.CSReturnType)
		out.WriteString(" ")
		out.WriteString(method.CSName)
		out.WriteString("(")
		out.WriteString(strings.Join(params, ", "))
		out.WriteString(")\n")
		out.WriteString("    {\n")

		if method.CSReturnType == "void" {
			if strings.Contains(method.Body, "_host.") && !strings.Contains(method.Body, "\n") {
				call := strings.TrimSuffix(method.Body, ";")
				out.WriteString("        HostDo(h => ")
				out.WriteString(strings.Replace(call, "_host", "h", 1))
				out.WriteString(");\n")
			} else if strings.Contains(method.Body, "\n") {
				for _, line := range strings.Split(method.Body, "\n") {
					out.WriteString("        ")
					out.WriteString(line)
					out.WriteString("\n")
				}
			} else {
				out.WriteString("        ")
				out.WriteString(method.Body)
				out.WriteString("\n")
			}
			out.WriteString("    }\n\n")
			continue
		}

		useHostBool := method.CSReturnType == "bool"
		if strings.Contains(method.Body, "_host.") && !strings.Contains(method.Body, "\n") {
			call := strings.TrimSuffix(strings.TrimPrefix(method.Body, "return "), ";")
			if useHostBool {
				out.WriteString("        return HostBool(h => ")
				out.WriteString(strings.Replace(call, "_host", "h", 1))
				out.WriteString(");\n")
			} else {
				out.WriteString("        return HostValue(")
				out.WriteString(csharpZeroValue(method.CSReturnType))
				out.WriteString(", h => ")
				out.WriteString(strings.Replace(call, "_host", "h", 1))
				out.WriteString(");\n")
			}
		} else {
			for _, line := range strings.Split(method.Body, "\n") {
				if strings.TrimSpace(line) == "" {
					continue
				}
				out.WriteString("        ")
				out.WriteString(line)
				out.WriteString("\n")
			}
		}

		out.WriteString("    }\n\n")
	}

	out.WriteString("}\n")
	return out.String()
}

func csharpZeroValue(typ string) string {
	switch typ {
	case "bool":
		return "false"
	case "double":
		return "0d"
	case "float":
		return "0f"
	case "long":
		return "0L"
	case "int":
		return "0"
	case "uint":
		return "0u"
	case "ulong":
		return "0UL"
	case "string":
		return "string.Empty"
	case "TimeSpan":
		return "TimeSpan.Zero"
	}
	if strings.HasPrefix(typ, "IReadOnlyList<") {
		inner := strings.TrimSuffix(strings.TrimPrefix(typ, "IReadOnlyList<"), ">")
		return "Array.Empty<" + inner + ">()"
	}
	if strings.HasPrefix(typ, "IReadOnlyDictionary<") {
		inner := strings.TrimSuffix(strings.TrimPrefix(typ, "IReadOnlyDictionary<"), ">")
		parts := strings.Split(inner, ",")
		if len(parts) == 2 {
			return "new Dictionary<" + strings.TrimSpace(parts[0]) + ", " + strings.TrimSpace(parts[1]) + ">()"
		}
		return "new Dictionary<object, object>()"
	}
	if strings.HasSuffix(typ, "?") {
		return "null"
	}
	if isKnownEnumTypeName(typ) {
		return "default(" + typ + ")"
	}
	return "default(" + typ + ")"
}

func isKnownEnumTypeName(name string) bool {
	return strings.HasSuffix(name, "Kind") || strings.HasSuffix(name, "Mode")
}

func csharpIdentifier(name string) string {
	if name == "" {
		return "Value"
	}
	parts := splitIdentifier(name)
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + strings.ToLower(part[1:])
	}
	return strings.Join(parts, "")
}

func csharpParameterName(name string) string {
	if name == "" {
		return "value"
	}
	id := csharpIdentifier(name)
	if id == "" {
		return "value"
	}
	return strings.ToLower(id[:1]) + id[1:]
}

func splitIdentifier(s string) []string {
	if s == "" {
		return nil
	}

	var parts []string
	var current bytes.Buffer
	flush := func() {
		if current.Len() == 0 {
			return
		}
		parts = append(parts, current.String())
		current.Reset()
	}

	runes := []rune(s)
	for i, r := range runes {
		if r == '_' {
			flush()
			continue
		}
		if i > 0 && isBoundary(runes[i-1], r, i+1 < len(runes) && isLower(runes[i+1])) {
			flush()
		}
		current.WriteRune(r)
	}
	flush()
	return parts
}

func isBoundary(prev, cur rune, nextIsLower bool) bool {
	if isLower(prev) && isUpper(cur) {
		return true
	}
	if isUpper(prev) && isUpper(cur) && nextIsLower {
		return true
	}
	if isDigit(prev) != isDigit(cur) {
		return true
	}
	return false
}

func isLower(r rune) bool {
	return r >= 'a' && r <= 'z'
}

func isUpper(r rune) bool {
	return r >= 'A' && r <= 'Z'
}

func isDigit(r rune) bool {
	return r >= '0' && r <= '9'
}
